import type { Metadata } from "next";
import Hero from "@/components/Hero";
import SubToolContent from "@/components/SubToolContent";

const siteUrl = "https://www.text-cleaner-ai.com";

export const metadata: Metadata = {
  title: "Remove AI Buzzwords — Strip \"Delve,\" \"Tapestry\" & Other Clichés",
  description:
    "Remove overused AI phrases like delve, tapestry, and testament to from your text. Free tool, works instantly in your browser.",
  keywords: [
    "remove ai words",
    "ai buzzwords",
  ],
  alternates: {
    canonical: "/remove-ai-words",
    languages: {
      en: "/remove-ai-words",
      es: "/es/remove-ai-words",
      de: "/de/remove-ai-words",
      fr: "/fr/remove-ai-words",
      it: "/it/remove-ai-words",
      pt: "/pt/remove-ai-words",
      ar: "/ar/remove-ai-words",
      ja: "/ja/remove-ai-words",
      nl: "/nl/remove-ai-words",
      tr: "/tr/remove-ai-words",
      id: "/id/remove-ai-words",
    },
  },
  openGraph: {
    title: "Remove AI Buzzwords — Strip \"Delve,\" \"Tapestry\" & Other Clichés",
    description:
      "Swap overused AI words for plainer alternatives, or remove them where they're not adding anything.",
    url: `${siteUrl}/remove-ai-words`,
  },
};

const removedItems = [
  {
    character: "Overused Verbs",
    unicode: "delve, elevate, unlock, leverage",
    description:
      "Words that show up so often in AI text that readers now spot them on sight.",
  },
  {
    character: "AI Metaphors",
    unicode: "tapestry, realm, testament to",
    description:
      "Dramatic figures of speech that make a reader assume text is AI-written and skim past it.",
  },
  {
    character: "Formal Filler Phrases",
    unicode: "\"in today's fast-paced world\"",
    description:
      "Formulaic openers that add length without adding meaning.",
  },
];

const howToSteps = [
  {
    title: "Paste AI Text",
    description:
      "Paste your article, essay, or copy generated by ChatGPT, Claude, or Gemini.",
  },
  {
    title: "Detect & Remove AI Words",
    description:
      "Our engine scans for 25+ overused AI words ('delve', 'tapestry', 'pivotal') and strips them.",
  },
  {
    title: "Copy Humanized Output",
    description:
      "Copy clean, natural-sounding plain text ready for publishing.",
  },
];

const benchmarks = [
  { name: "Google Chrome", time: "Instant" },
  { name: "Apple Safari", time: "Instant" },
  { name: "Mozilla Firefox", time: "Instant" },
];

const valueProps = [
  {
    title: "100% In-Browser Privacy",
    desc: "Your text is processed locally in browser memory. Nothing is sent to external servers or logged in databases.",
    icon: "enhanced_encryption",
  },
  {
    title: "Instant Processing",
    desc: "Zero network latency, zero API rate limits, and zero queues. Analysis runs immediately as you type or paste.",
    icon: "offline_bolt",
  },
  {
    title: "Advanced Heuristic Detection",
    desc: "Scans sentence length burstiness, passive voice structure, and overused LLM transition phrase clichés.",
    icon: "hub",
  },
  {
    title: "Multi-Language Static Support",
    desc: "Supports 11 static language routes ensuring seamless user experience across international audiences.",
    icon: "language",
  },
  {
    title: "Visual Highlight Breakdown",
    desc: "Color-coded inline sentence markers reveal exact locations of suspected AI phrases and formatting quirks.",
    icon: "splitscreen",
  },
  {
    title: "Zero Account Required",
    desc: "No signups, no subscriptions, and no credit card required. Free, open, and accessible to everyone.",
    icon: "no_accounts",
  },
];

const faqs = [
  {
    question: "Why do these specific words keep showing up in AI text?",
    answer:
      "Large language models are trained to sound polished and were rewarded during training for certain \"safe,\" formal-sounding word choices. Those choices became a tic, and readers have learned to recognize them.",
  },
  {
    question: "Will removing these words make my writing sound robotic in a different way?",
    answer:
      "No — the goal is plainer, more direct language, which usually reads more naturally, not less.",
  },
];

const webAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "Remove AI Words Tool",
  url: `${siteUrl}/remove-ai-words`,
  description: "Remove overused AI phrases like delve, tapestry, and testament to from your text.",
  applicationCategory: "UtilitiesApplication",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
};

const howToJsonLd = {
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to Remove Overused AI Words from Text",
  step: howToSteps.map((step) => ({
    "@type": "HowToStep",
    name: step.title,
    text: step.description,
  })),
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
};

export default function RemoveAIWordsPage() {
  return (
    <div className="container mx-auto px-4 md:px-8 py-space-lg flex flex-col w-full space-y-12 md:space-y-16">
      <span className="sr-only">
        Remove AI Words &amp; Buzzwords — Strip Delve, Tapestry &amp; Clichés Online | Text Cleaner AI
      </span>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <Hero
        heading="Remove AI Buzzwords From Your Text"
        subheading="Swap overused AI phrases like delve, tapestry, and testament to for plainer alternatives — free and instant."
        initialOptions={{
          removeAIWords: true,
          removeMarkdown: true,
          removeTrailingWhitespace: true,
          removeHiddenCharacters: true,
          removeAIFluff: true,
        }}
      />
      <SubToolContent
        title="Remove AI Words"
        badgeLabel="Linguistic Telemetry"
        badgeIcon="psychology"
        directAnswerTitle="Why Remove Words Like &quot;Delve&quot; and &quot;Tapestry&quot;?"
        directAnswerText="Some words show up so often in AI-generated text that readers now spot them on sight: delve, tapestry, testament to, boasts, elevate, unlock, seamless, landscape, &quot;in today's fast-paced world,&quot; &quot;it's important to note that.&quot; Even when the underlying writing is good, these words are enough to make a reader assume it's AI-written — and skim past it. This tool finds those words and phrases and swaps them for plainer alternatives, or removes them where they're not adding anything."
        beforeBadgeText="[ALERT]"
        afterBadgeText="[SANITIZED]"
        beforeExample={
          <div className="space-y-2">
            <p>
              In today&apos;s digital landscape, we{" "}
              <mark className="bg-error-container text-on-error-container px-1 rounded font-semibold">
                delve
              </mark>{" "}
              into this{" "}
              <mark className="bg-error-container text-on-error-container px-1 rounded font-semibold">
                rich tapestry
              </mark>{" "}
              of modern AI tools.
            </p>
            <p>
              It is a{" "}
              <mark className="bg-error-container text-on-error-container px-1 rounded font-semibold">
                testament
              </mark>{" "}
              to{" "}
              <mark className="bg-error-container text-on-error-container px-1 rounded font-semibold">
                pivotal
              </mark>{" "}
              innovation.
            </p>
          </div>
        }
        afterExample={
          <div className="space-y-2 text-on-surface">
            <p>We look into this modern web tools.</p>
            <p>It shows innovation.</p>
          </div>
        }
        beforeNote="Contains: delve, rich tapestry, testament, pivotal, in today's digital landscape"
        afterNote="Purged: Natural human vocabulary & organic sentence flow"
        removedItems={removedItems}
        streamChart={false}
        activeSuiteToolHref="/remove-ai-words"
        howToSteps={howToSteps}
        benchmarksTitle="Browser Engine Latency"
        benchmarks={benchmarks}
        valueProps={valueProps}
        faqs={faqs}
      />
    </div>
  );
}
