import type { Metadata } from "next";
import Hero from "@/components/Hero";
import SubToolContent from "@/components/SubToolContent";

const siteUrl = "https://aitextcleaner.com";

export const metadata: Metadata = {
  title: "Remove AI Words & Buzzwords — Strip Delve, Tapestry & Clichés Online",
  description:
    "Detect and remove overused AI words like 'delve', 'tapestry', 'realm', 'pivotal', and 'foster' from ChatGPT, Claude, and Gemini text. 100% free & client-side.",
  keywords: [
    "remove ai words",
    "remove chatgpt buzzwords",
    "delve tapestry remover",
    "ai cliché stripper",
    "humanize ai text words",
  ],
  alternates: {
    canonical: "/remove-ai-words",
  },
  openGraph: {
    title: "Remove AI Words & Buzzwords — Strip Delve, Tapestry & Clichés Online",
    description:
      "Instantly detect and strip robotic AI buzzwords like delve, tapestry, and realm from your writing.",
    url: `${siteUrl}/remove-ai-words`,
  },
};

const removedItems = [
  {
    character: "Overused Verbs & Action Words",
    unicode: "delve / embark / harness / navigate",
    description: "Tell-tale AI verbs that make written content sound corporate and machine-generated.",
  },
  {
    character: "AI Fluff & Metaphors",
    unicode: "tapestry / realm / beacon / testament",
    description: "Dramatic AI metaphors frequently flagged by readers and AI content detectors.",
  },
  {
    character: "Corporate Filler Connectives",
    unicode: "in today's digital landscape / furthermore",
    description: "Formulaic AI sentence openers that bore readers and dilute impact.",
  },
];

const howToSteps = [
  {
    title: "Paste AI Text",
    description: "Paste your article, essay, or copy generated by ChatGPT, Claude, or Gemini.",
  },
  {
    title: "Detect & Remove AI Words",
    description: "Our engine scans for 25+ overused AI words ('delve', 'tapestry', 'pivotal') and strips them.",
  },
  {
    title: "Copy Humanized Output",
    description: "Copy clean, natural-sounding plain text ready for publishing.",
  },
];

const faqs = [
  {
    question: "Why does ChatGPT overuse words like 'delve' and 'tapestry'?",
    answer:
      "Language models like ChatGPT were trained on high-volume formal web corpora where words like 'delve', 'tapestry', and 'testament' appeared frequently. The model defaults to these words when aiming for a formal or professional tone.",
  },
  {
    question: "Does removing AI buzzwords help bypass AI detectors?",
    answer:
      "Removing repetitive AI buzzwords and robotic openers significantly improves human readability and reduces the predictability patterns that AI detectors look for.",
  },
  {
    question: "Which specific AI words are detected and removed?",
    answer:
      "Our filter targets 25+ overused words including: delve, tapestry, testament, pivotal, beacon, foster, realm, crucial, seamless, bustling, harness, leverage, holistic, bespoke, cutting-edge, game-changer, paramount, embark, navigate, in today's digital landscape, furthermore, moreover, and in conclusion.",
  },
  {
    question: "Will removing these words ruin sentence grammar?",
    answer:
      "The tool cleanly strips target cliché words and normalizes adjacent double spaces. You can review the output or use Visual Diff Mode to verify sentence flow.",
  },
  {
    question: "Is this AI Buzzword Stripper free?",
    answer:
      "Yes! It is 100% free with unlimited usage and no sign-up requirement.",
  },
];

const webAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "Remove AI Words Tool",
  url: `${siteUrl}/remove-ai-words`,
  description: "Free tool to strip overused AI buzzwords like delve, tapestry, and realm.",
  applicationCategory: "UtilitiesApplication",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
};

const howToJsonLd = {
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to Remove Overused AI Words from Text",
  step: howToSteps.map((step) => ({
    "@type": "HowToStep",
    name: step.title,
    text: step.description,
  })),
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
};

export default function RemoveAIWordsPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <Hero
        heading="Remove AI Words & Buzzwords"
        subheading="Instantly detect and strip overused robotic AI words ('delve', 'tapestry', 'realm', 'pivotal') and cliché openers from your writing."
        initialOptions={{
          removeAIWords: true,
          removeMarkdown: true,
          removeTrailingWhitespace: true,
          removeHiddenCharacters: true,
          removeAIFluff: true,
        }}
      />
      <SubToolContent
        title="Remove AI Words"
        directAnswerTitle="Why Remove AI Buzzwords Like 'Delve' & 'Tapestry'?"
        directAnswerText="Readers and AI content detectors immediately recognize text generated by ChatGPT due to overused cliché words like 'delve', 'tapestry', 'testament', 'pivotal', and 'realm'. Our tool automatically detects and removes these tell-tale AI buzzwords, helping your content sound natural and authentic."
        beforeExample={"In today's digital landscape, we delve into this rich tapestry of modern AI tools.\nIt is a testament to pivotal innovation."}
        afterExample={"We look into this modern web tools.\nIt shows innovation."}
        removedItems={removedItems}
        howToSteps={howToSteps}
        faqs={faqs}
      />
    </>
  );
}
