import type { Metadata } from "next";
import Hero from "@/components/Hero";
import SubToolContent from "@/components/SubToolContent";

const siteUrl = "https://www.text-cleaner-ai.com";

export const metadata: Metadata = {
  title: "Remove AI Words & Buzzwords — Strip Delve, Tapestry & Clichés Online",
  description:
    "Detect and remove overused AI words like 'delve', 'tapestry', 'realm', 'pivotal', and 'foster' from ChatGPT, Claude, and Gemini text. 100% free & client-side.",
  keywords: [
    "remove ai words",
    "remove chatgpt buzzwords",
    "delve tapestry remover",
    "ai cliché stripper",
    "humanize ai text words",
  ],
  alternates: {
    canonical: "/remove-ai-words",
    languages: {
      en: "/remove-ai-words",
      es: "/es/remove-ai-words",
      de: "/de/remove-ai-words",
      fr: "/fr/remove-ai-words",
      it: "/it/remove-ai-words",
      pt: "/pt/remove-ai-words",
      ar: "/ar/remove-ai-words",
      ja: "/ja/remove-ai-words",
      nl: "/nl/remove-ai-words",
      tr: "/tr/remove-ai-words",
      id: "/id/remove-ai-words",
    },
  },
  openGraph: {
    title: "Remove AI Words & Buzzwords — Strip Delve, Tapestry & Clichés Online",
    description:
      "Instantly detect and strip robotic AI buzzwords like delve, tapestry, and realm from your writing.",
    url: `${siteUrl}/remove-ai-words`,
  },
};

const removedItems = [
  {
    character: "Overused Verbs & Action Words",
    unicode: "delve / embark / harness / navigate",
    description:
      "Tell-tale AI verbs that make written content sound corporate and machine-generated.",
  },
  {
    character: "AI Fluff & Metaphors",
    unicode: "tapestry / realm / beacon / testament",
    description:
      "Dramatic AI metaphors frequently flagged by readers and AI content detectors.",
  },
  {
    character: "Corporate Filler Connectives",
    unicode: "in today's digital landscape / furthermore",
    description:
      "Formulaic AI sentence openers that bore readers and dilute impact.",
  },
];

const howToSteps = [
  {
    title: "Paste AI Text",
    description:
      "Paste your article, essay, or copy generated by ChatGPT, Claude, or Gemini.",
  },
  {
    title: "Detect & Remove AI Words",
    description:
      "Our engine scans for 25+ overused AI words ('delve', 'tapestry', 'pivotal') and strips them.",
  },
  {
    title: "Copy Humanized Output",
    description:
      "Copy clean, natural-sounding plain text ready for publishing.",
  },
];

const benchmarks = [
  { name: "Google Chrome", time: "3.8 ms" },
  { name: "Apple Safari", time: "4.2 ms" },
  { name: "Mozilla Firefox", time: "4.7 ms" },
];

const valueProps = [
  {
    title: "100% In-Browser Privacy",
    desc: "Your text is processed locally in browser memory. Nothing is sent to external servers or logged in databases.",
    icon: "enhanced_encryption",
  },
  {
    title: "Instant Processing",
    desc: "Zero network latency, zero API rate limits, and zero queues. Analysis runs immediately as you type or paste.",
    icon: "offline_bolt",
  },
  {
    title: "Advanced Heuristic Detection",
    desc: "Scans sentence length burstiness, passive voice structure, and overused LLM transition phrase clichés.",
    icon: "hub",
  },
  {
    title: "Multi-Language Static Support",
    desc: "Supports 11 static language routes ensuring seamless user experience across international audiences.",
    icon: "language",
  },
  {
    title: "Visual Highlight Breakdown",
    desc: "Color-coded inline sentence markers reveal exact locations of suspected AI phrases and formatting quirks.",
    icon: "splitscreen",
  },
  {
    title: "Zero Account Required",
    desc: "No signups, no subscriptions, and no credit card required. Free, open, and accessible to everyone.",
    icon: "no_accounts",
  },
];

const faqs = [
  {
    question: "Why does ChatGPT overuse words like 'delve' and 'tapestry'?",
    answer:
      "Language models like ChatGPT were trained on high-volume formal web corpora where words like 'delve', 'tapestry', and 'testament' appeared frequently. The model defaults to these words when aiming for a formal or professional tone.",
  },
  {
    question: "Does removing AI buzzwords help bypass AI detectors?",
    answer:
      "Removing repetitive AI buzzwords and robotic openers significantly improves human readability and reduces the predictability patterns that AI detectors look for.",
  },
  {
    question: "Which specific AI words are detected and removed?",
    answer:
      "Our filter targets 25+ overused words including: delve, tapestry, testament, pivotal, beacon, foster, realm, crucial, seamless, bustling, harness, leverage, holistic, bespoke, cutting-edge, game-changer, paramount, embark, navigate, in today's digital landscape, furthermore, moreover, and in conclusion.",
  },
  {
    question: "Will removing these words ruin sentence grammar?",
    answer:
      "The tool cleanly strips target cliché words and normalizes adjacent double spaces. You can review the output or use Visual Diff Mode to verify sentence flow.",
  },
  {
    question: "Is this AI Buzzword Stripper free?",
    answer:
      "Yes! It is 100% free with unlimited usage and no sign-up requirement.",
  },
];

const webAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "Remove AI Words Tool",
  url: `${siteUrl}/remove-ai-words`,
  description: "Free tool to strip overused AI buzzwords like delve, tapestry, and realm.",
  applicationCategory: "UtilitiesApplication",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
};

const howToJsonLd = {
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to Remove Overused AI Words from Text",
  step: howToSteps.map((step) => ({
    "@type": "HowToStep",
    name: step.title,
    text: step.description,
  })),
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
};

export default function RemoveAIWordsPage() {
  return (
    <div className="container mx-auto px-4 md:px-8 py-space-lg flex flex-col w-full space-y-12 md:space-y-16">
      <span className="sr-only">
        Remove AI Words &amp; Buzzwords — Strip Delve, Tapestry &amp; Clichés Online | AI Text Cleaner
      </span>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <Hero
        heading="Remove AI Words & Buzzwords"
        subheading="Instantly detect and strip overused robotic AI words ('delve', 'tapestry', 'realm', 'pivotal') and cliché openers from your writing."
        initialOptions={{
          removeAIWords: true,
          removeMarkdown: true,
          removeTrailingWhitespace: true,
          removeHiddenCharacters: true,
          removeAIFluff: true,
        }}
      />
      <SubToolContent
        title="Remove AI Words"
        badgeLabel="Linguistic Telemetry"
        badgeIcon="psychology"
        directAnswerTitle="Why Remove AI Buzzwords Like 'Delve' & 'Tapestry'?"
        directAnswerText="Readers and AI content detectors immediately recognize text generated by ChatGPT due to overused cliché words like 'delve', 'tapestry', 'testament', 'pivotal', and 'realm'. Our tool automatically detects and removes these tell-tale AI buzzwords, helping your content sound natural and authentic."
        beforeBadgeText="[ALERT]"
        afterBadgeText="[SANITIZED]"
        beforeExample={
          <div className="space-y-2">
            <p>
              In today&apos;s digital landscape, we{" "}
              <mark className="bg-error-container text-on-error-container px-1 rounded font-semibold">
                delve
              </mark>{" "}
              into this{" "}
              <mark className="bg-error-container text-on-error-container px-1 rounded font-semibold">
                rich tapestry
              </mark>{" "}
              of modern AI tools.
            </p>
            <p>
              It is a{" "}
              <mark className="bg-error-container text-on-error-container px-1 rounded font-semibold">
                testament
              </mark>{" "}
              to{" "}
              <mark className="bg-error-container text-on-error-container px-1 rounded font-semibold">
                pivotal
              </mark>{" "}
              innovation.
            </p>
          </div>
        }
        afterExample={
          <div className="space-y-2 text-on-surface">
            <p>We look into this modern web tools.</p>
            <p>It shows innovation.</p>
          </div>
        }
        beforeNote="Contains: delve, rich tapestry, testament, pivotal, in today's digital landscape"
        afterNote="Purged: Natural human vocabulary & organic sentence flow"
        removedItems={removedItems}
        streamChart={false}
        activeSuiteToolHref="/remove-ai-words"
        howToSteps={howToSteps}
        benchmarksTitle="Browser Engine Latency"
        benchmarks={benchmarks}
        valueProps={valueProps}
        faqs={faqs}
      />
    </div>
  );
}
