import type { Metadata } from "next";
import AIDetectorUI from "@/components/AIDetectorUI";
import SubToolContent from "@/components/SubToolContent";
import { generateSubToolMetadata } from "@/components/LocalizedSubToolLayout";
import { LANGUAGES } from "@/lib/i18n/dictionaries";

export const dynamic = "force-static";

export function generateStaticParams() {
  return Object.keys(LANGUAGES)
    .filter((code) => code !== "en")
    .map((lang) => ({ lang }));
}

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }): Promise<Metadata> {
  const { lang } = await params;
  return generateSubToolMetadata(lang, "aiTextDetector", "ai-text-detector");
}

const removedItems = [
  {
    character: "Sentence Length Variation",
    unicode: "Burstiness",
    description: "How much sentence length varies across the text — a flat, even rhythm is one common sign of AI writing.",
  },
  {
    character: "Common AI Transition Phrases",
    unicode: "furthermore, in conclusion",
    description: "Words like \"furthermore,\" \"in conclusion,\" and \"it's worth noting\" show up more often in AI text.",
  },
  {
    character: "Repetition in Sentence Structure",
    unicode: "n/a",
    description: "Sentences that follow the same shape and length repeatedly.",
  },
  {
    character: "Overall Predictability",
    unicode: "n/a",
    description: "How closely the writing follows the most statistically likely word choices.",
  },
];

const howToSteps = [
  {
    title: "Paste Draft Text",
    description: "Paste content generated by ChatGPT, Claude, Gemini, or Copilot into the raw text input.",
  },
  {
    title: "Check AI Probability",
    description: "Our browser engine scores sentence-length burstiness, cliché phrase density, and passive voice live.",
  },
  {
    title: "Inspect Highlights & Humanize",
    description: "Review color-coded sentence badges and click 'Humanize & Copy' to sanitize your writing.",
  },
];

const faqs = [
  {
    question: "How accurate is this?",
    answer:
      "No AI detector is fully accurate, and this one is no exception. Use it as a starting point, not proof.",
  },
  {
    question: "Does it store the text I check?",
    answer: "No. Everything runs in your browser.",
  },
  {
    question: "Can this get a human falsely flagged as AI?",
    answer:
      "Yes, that can happen with any AI detector. That's exactly why the score should be treated as a hint, not a fact.",
  },
];

export default async function LocalizedAITextDetectorPage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  const l = LANGUAGES[lang] || LANGUAGES.en;
  const isRtl = l.dir === "rtl";
  const tool = l.subtools?.aiTextDetector || LANGUAGES.en.subtools.aiTextDetector!;

  return (
    <div dir={isRtl ? "rtl" : "ltr"} className={isRtl ? "font-arabic" : ""}>
      <AIDetectorUI
        heading={tool.heading}
        subheading={tool.subheading}
      />
      <SubToolContent
        title={tool.heading}
        directAnswerTitle={tool.heading}
        directAnswerText={tool.subheading}
        beforeExample="In today's fast-paced world, artificial intelligence serves as a testament to human innovation. Furthermore, delving into this digital realm allows us to foster pivotal advancements."
        afterExample="Flagged: low sentence-length variation, 3 common AI transition phrases"
        removedItems={removedItems}
        howToSteps={howToSteps}
        faqs={faqs}
      />
    </div>
  );
}
