import type { Metadata } from "next";
import AIDetectorUI from "@/components/AIDetectorUI";
import SubToolContent from "@/components/SubToolContent";

export const dynamic = "force-static";

const languages = ["es", "de", "fr", "it", "pt", "ar", "ja", "nl", "tr", "id"];

export function generateStaticParams() {
  return languages.map((lang) => ({ lang }));
}

export function generateMetadata(): Metadata {
  return {
    title: "Free AI Text Detector (ChatGPT, GPT-4, Claude & Gemini) — 100% In-Browser",
    description:
      "Free online AI text detector. Check if text was written by ChatGPT, Claude, GPT-4, or Gemini. Highlight overused clichés, sentence monotony, and passive-voice patterns.",
  };
}

const removedItems = [
  {
    character: "Sentence Uniformity Check",
    unicode: "Length Variance",
    description: "Flags sentences whose length nearly matches the paragraph average — a common structural tell in AI-generated prose.",
  },
  {
    character: "Burstiness Monotony",
    unicode: "Sentence Length",
    description: "Measures how much sentence lengths vary across the whole text. Low variation (a monotonous rhythm) is scored as AI-typical.",
  },
  {
    character: "AI Cliché Phrase Density",
    unicode: "Delve, Tapestry, Realm",
    description: "Flags overused RLHF training phrases (delve, tapestry, testament to, furthermore).",
  },
  {
    character: "Passive AI Structure",
    unicode: "is / was + verb + by",
    description: "Identifies formal passive voice patterns common in automated AI drafts.",
  },
];

const howToSteps = [
  {
    title: "Paste Draft Text",
    description: "Paste content generated by ChatGPT, Claude, Gemini, or Copilot into the raw text input.",
  },
  {
    title: "Check AI Probability",
    description: "Our browser engine scores sentence-length burstiness, cliché phrase density, and passive voice live.",
  },
  {
    title: "Inspect Highlights & Humanize",
    description: "Review color-coded sentence badges and click 'Humanize & Copy' to sanitize your writing.",
  },
];

const faqs = [
  {
    question: "How does this AI Text Detector work?",
    answer:
      "Our AI Text Detector analyzes sentence length variance (burstiness), passive voice structure, and overused AI cliché phrases (delve, tapestry, realm, testament to) to compute a Human vs AI probability estimate.",
  },
  {
    question: "Is my text saved or uploaded to cloud servers?",
    answer:
      "No! Processing runs 100% locally in your browser memory. Zero text is logged, uploaded, or stored.",
  },
  {
    question: "Which AI models can this detector identify?",
    answer:
      "It detects structural writing patterns characteristic of ChatGPT (GPT-3.5/GPT-4o), Claude 3.5 Sonnet, Google Gemini, Microsoft Copilot, and open-source LLMs.",
  },
  {
    question: "Can I humanize detected AI text with one click?",
    answer:
      "Yes. Click 'Humanize & Copy Text' to strip robotic clichés and restore natural human sentence variation.",
  },
];

export default async function LocalizedAITextDetectorPage({ params }: { params: Promise<{ lang: string }> }) {
  await params;
  return (
    <>
      <AIDetectorUI
        heading="Free AI Text Detector (ChatGPT, GPT-4, Claude & Gemini)"
        subheading="Check if your text was generated by AI models in seconds. Highlight overused clichés, sentence monotony, and passive-voice patterns."
      />
      <SubToolContent
        title="AI Text Detector"
        directAnswerTitle="How to Detect AI Generated Text & Analyze Writing Probability"
        directAnswerText="AI text models generate language by calculating highest-probability next words, which creates distinct writing fingerprints: uniform sentence lengths (low burstiness), passive voice constructions, and reliance on specific RLHF clichés ('delve into', 'vibrant tapestry', 'testament to'). Our client-side AI Text Detector highlights these exact markers in real-time."
        beforeExample="In today's fast-paced world, artificial intelligence serves as a testament to human innovation. Furthermore, delving into this digital realm allows us to foster pivotal advancements."
        afterExample="AI Probability: 92% | Human Score: 8% | 3 Clichés Highlighted"
        removedItems={removedItems}
        howToSteps={howToSteps}
        faqs={faqs}
      />
    </>
  );
}
