'use client';

import { useMemo, useState } from "react";
import {
  Bot,
  Copy,
  Check,
  RotateCcw,
  ShieldCheck,
  Sparkles,
  Wand2,
  FileText,
  AlertTriangle,
  Zap,
  Download,
  Upload,
} from "lucide-react";
import copy from "copy-to-clipboard";
import ToolDrawer from "@/components/ToolDrawer";
import { detectAIText, getSampleAIDetectionText, type AIDetectionResult } from "@/lib/detectAI";
import { humanizeText } from "@/lib/humanizeText";
import { getTextStats } from "@/lib/textStats";
import { trackCleanTextRun, trackCopyText, trackDownloadFile } from "@/lib/analytics";

const defaultSample = getSampleAIDetectionText();

export interface AIDetectorUIProps {
  heading?: string;
  subheading?: string;
}

export default function AIDetectorUI({ heading, subheading }: AIDetectorUIProps = {}) {
  const [input, setInput] = useState("");
  const [result, setResult] = useState<AIDetectionResult | null>(null);
  const [copied, setCopied] = useState(false);

  const inputStats = useMemo(() => getTextStats(input), [input]);
  const hasText = input.trim().length > 0;

  function handleAnalyze() {
    if (!input.trim()) return;
    const res = detectAIText(input);
    setResult(res);
    setCopied(false);
    trackCleanTextRun({
      toolName: "ai_text_detector",
      inputWords: inputStats.words,
      inputChars: inputStats.characters,
      changesCount: res.aiWordsFound.length,
    });
  }

  function handleSampleText() {
    const sample = getSampleAIDetectionText();
    setInput(sample);
    const res = detectAIText(sample);
    setResult(res);
    trackCleanTextRun({
      toolName: "ai_text_detector_sample",
      inputWords: getTextStats(sample).words,
      inputChars: sample.length,
      changesCount: res.aiWordsFound.length,
    });
  }

  function handleFileUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const uploadedFile = e.target.files?.[0];
    if (!uploadedFile) return;

    const reader = new FileReader();
    reader.onload = (evt) => {
      const textContent = evt.target?.result as string;
      if (textContent) {
        setInput(textContent);
        setResult(detectAIText(textContent));
      }
    };
    reader.readAsText(uploadedFile);
  }

  function handleHumanizeAndCopy() {
    if (!input.trim()) return;
    const hum = humanizeText(input);
    copy(hum.humanizedText);
    setCopied(true);
    trackCopyText({ toolName: "ai_text_detector_humanize", copyFormat: "plain_text" });
    setTimeout(() => setCopied(false), 1500);
  }

  function handleDownloadReport() {
    if (!result) return;
    trackDownloadFile({ toolName: "ai_text_detector", fileType: "txt" });
    const content = `AI TEXT DETECTION REPORT
=========================
Human Score: ${result.humanScore}%
AI Generated Score: ${result.aiScore}%
Classification: ${result.classification}
Total Words: ${result.totalWords}
Total Sentences: ${result.totalSentences}

AI Clichés Found: ${result.aiWordsFound.join(", ") || "None"}

FULL INPUT TEXT:
${input}
`;
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "ai-detection-report.txt";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  function handleReset() {
    setInput("");
    setResult(null);
    setCopied(false);
  }

  return (
    <section className="bg-surface py-6 md:py-8">
      <div className="container mx-auto flex flex-col items-center gap-4 md:gap-5 px-4 md:px-6">
        {/* Top Header */}
        <div className="flex max-w-4xl md:max-w-5xl flex-col items-center gap-2 text-center">
          <h1 className="font-display-lg text-display-lg text-on-surface tracking-tight font-semibold">
            {heading ?? "Free AI Text Detector (ChatGPT, GPT-4, Claude & Gemini)"}
          </h1>
          <p className="font-body-lg text-body-lg text-on-surface-variant leading-relaxed max-w-4xl mx-auto">
            {subheading ??
              "Check if your text was generated by AI models in seconds. Highlight overused clichés, sentence monotony, and passive-voice patterns."}
          </p>
        </div>

        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleAnalyze();
          }}
          className="w-full rounded-xl border border-surface-container-highest/80 bg-surface-container-lowest shadow-md overflow-hidden"
        >
          {/* Top Tool Drawer Bar */}
          <ToolDrawer />

          <div className="p-6 sm:p-8">
            {/* Quick Action Presets Bar */}
            <div className="mb-6 flex flex-wrap items-center justify-between gap-2 border-b border-surface-container-highest/80 pb-4">
              <div className="flex flex-wrap items-center gap-2">
                <span className="font-code-stat text-code-stat uppercase text-outline mr-1">
                  Sample Drafts:
                </span>
                <button
                  type="button"
                  onClick={() => {
                    const sample = getSampleAIDetectionText();
                    setInput(sample);
                    setResult(detectAIText(sample));
                  }}
                  className="flex cursor-pointer items-center gap-1 rounded-md border border-neutral-300 bg-white px-2.5 py-1 text-body-xs font-medium text-neutral-700 transition-colors duration-200 hover:border-primary-500 hover:bg-primary-50 hover:text-primary-700"
                >
                  <Bot className="h-3 w-3 text-primary-600" />
                  ChatGPT Draft (High AI %)
                </button>
                <button
                  type="button"
                  onClick={() => {
                    const sample =
                      "I walked down to the local hardware store this morning to buy a new wrench. The cashier was helpful and recommended a sturdy brand.";
                    setInput(sample);
                    setResult(detectAIText(sample));
                  }}
                  className="flex cursor-pointer items-center gap-1 rounded-md border border-neutral-300 bg-white px-2.5 py-1 text-body-xs font-medium text-neutral-700 transition-colors duration-200 hover:border-primary-500 hover:bg-primary-50 hover:text-primary-700"
                >
                  <Zap className="h-3 w-3 text-emerald-600" />
                  Human Essay (100% Human)
                </button>
              </div>

              {/* Upload File */}
              <label className="flex cursor-pointer items-center gap-1 text-body-xs font-bold text-primary-700 hover:underline">
                <Upload className="h-3.5 w-3.5" />
                Upload .txt file
                <input type="file" accept=".txt,.md,.doc,.docx" className="hidden" onChange={handleFileUpload} />
              </label>
            </div>

            <div className="grid gap-6 sm:grid-cols-2">
              {/* Input Card */}
              <div className="flex flex-col gap-2 text-left">
                <div className="flex items-center justify-between">
                  <p className="flex items-center gap-1.5 text-body-sm font-bold text-neutral-700">
                    <FileText className="h-4 w-4 text-neutral-500" aria-hidden="true" />
                    Raw Text Input
                  </p>
                  <div className="flex items-center gap-3">
                    <button
                      type="button"
                      onClick={handleSampleText}
                      className="flex cursor-pointer items-center gap-1 text-body-xs font-bold text-primary-700 hover:underline"
                    >
                      <Wand2 className="h-3.5 w-3.5" />
                      Try Sample AI Text
                    </button>
                    <p className="text-body-sm text-neutral-500">
                      {inputStats.words} words, {inputStats.characters} chars
                    </p>
                  </div>
                </div>
                <textarea
                  rows={9}
                  value={input}
                  onChange={(e) => {
                    const val = e.target.value;
                    setInput(val);
                    if (val.trim()) {
                      setResult(detectAIText(val));
                    } else {
                      setResult(null);
                    }
                  }}
                  placeholder="Paste text here to check for AI probability, sentence burstiness, and cliché patterns..."
                  className="w-full rounded-lg border border-neutral-300 bg-neutral-0 p-4 text-body-sm text-neutral-900 placeholder-neutral-400 transition-colors duration-200 focus:border-primary-500 focus:outline-none"
                />
              </div>

              {/* AI Score & Highlighted Visualizer Output */}
              <div className="flex flex-col gap-3 text-left">
                <div className="flex items-center justify-between">
                  <p className="flex items-center gap-1.5 text-body-sm font-bold text-neutral-700">
                    <Sparkles className="h-4 w-4 text-primary-600" aria-hidden="true" />
                    AI Probability &amp; Highlighted Analysis
                  </p>
                  {result && (
                    <span
                      className={`text-body-xs font-bold px-2.5 py-0.5 rounded ${
                        result.aiScore > 40
                          ? "bg-amber-100 text-amber-900 border border-amber-200"
                          : "bg-emerald-100 text-emerald-900 border border-emerald-200"
                      }`}
                    >
                      {result.classification}
                    </span>
                  )}
                </div>

                {/* Speedometer Radial Gauge Meter */}
                {result && (
                  <div className="flex items-center justify-around bg-neutral-50 p-3 rounded-lg border border-neutral-200">
                    {/* Radial Gauge SVG */}
                    <div className="relative flex flex-col items-center justify-center">
                      <svg className="w-24 h-24 transform -rotate-90" viewBox="0 0 36 36">
                        <path
                          className="text-neutral-200"
                          strokeWidth="3.8"
                          stroke="currentColor"
                          fill="none"
                          d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                        />
                        <path
                          className={result.humanScore >= 60 ? "text-emerald-500" : "text-amber-500"}
                          strokeDasharray={`${result.humanScore}, 100`}
                          strokeWidth="3.8"
                          strokeLinecap="round"
                          stroke="currentColor"
                          fill="none"
                          d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                        />
                      </svg>
                      <div className="absolute flex flex-col items-center text-center">
                        <span className="text-h4 font-extrabold text-neutral-900 leading-none">
                          {result.humanScore}%
                        </span>
                        <span className="text-[10px] font-bold uppercase text-neutral-500 mt-0.5">
                          Human
                        </span>
                      </div>
                    </div>

                    <div className="flex flex-col gap-1.5 text-left">
                      <div className="flex items-center gap-2">
                        <span className="h-3 w-3 rounded-full bg-emerald-500 inline-block"></span>
                        <span className="text-body-xs text-neutral-700">
                          Human Score: <strong className="text-neutral-900">{result.humanScore}%</strong>
                        </span>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className="h-3 w-3 rounded-full bg-amber-500 inline-block"></span>
                        <span className="text-body-xs text-neutral-700">
                          AI Probability: <strong className="text-neutral-900">{result.aiScore}%</strong>
                        </span>
                      </div>
                      <p className="text-[11px] text-neutral-500 mt-1 max-w-[180px] leading-tight">
                        {result.aiWordsFound.length > 0
                          ? `${result.aiWordsFound.length} AI clichés detected.`
                          : "Natural human rhythm pattern."}
                      </p>
                    </div>
                  </div>
                )}

                {/* Highlighted Sentence Breakdown View */}
                <div className="w-full min-h-[160px] max-h-[200px] overflow-y-auto rounded-lg border border-neutral-300 bg-white p-4 text-body-sm text-neutral-900 leading-relaxed">
                  {result && result.segments.length > 0 ? (
                    result.segments.map((seg) => (
                      <span
                        key={seg.id}
                        className={`inline transition-colors rounded px-1 py-0.5 mx-0.5 cursor-help ${
                          seg.isAI
                            ? "bg-amber-100 text-amber-950 border-b-2 border-amber-400 hover:bg-amber-200"
                            : "bg-emerald-50/80 text-emerald-950 hover:bg-emerald-100"
                        }`}
                        title={seg.reason}
                      >
                        {seg.text}{" "}
                      </span>
                    ))
                  ) : (
                    <span className="text-neutral-400 italic">
                      Sentence breakdown with color-coded AI highlights will render here...
                    </span>
                  )}
                </div>
              </div>
            </div>

            {/* AI Cliché Summary Pill Bar */}
            {result && result.aiWordsFound.length > 0 && (
              <div className="mt-6 flex flex-col gap-2 border-t border-neutral-200 pt-6 text-left">
                <p className="text-body-sm font-bold text-amber-900 flex items-center gap-1.5">
                  <AlertTriangle className="h-4 w-4 text-amber-600" />
                  Suspected AI Cliché Vocabulary Found:
                </p>
                <div className="flex flex-wrap gap-2">
                  {result.aiWordsFound.map((word) => (
                    <span
                      key={word}
                      className="inline-flex items-center gap-1 rounded-md bg-amber-100 px-2.5 py-1 text-body-xs font-bold text-amber-900 border border-amber-200"
                    >
                      ⚠️ {word}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Bottom Action Buttons Bar */}
            <div className="mt-6 flex flex-col sm:flex-row flex-wrap items-center justify-between gap-3 border-t border-surface-container-highest/80 pt-4">
              <div className="flex flex-wrap items-center gap-3 w-full sm:w-auto">
                <button
                  type="submit"
                  disabled={!hasText}
                  className="w-full sm:w-auto px-6 py-2.5 rounded-lg bg-primary-container hover:bg-primary text-on-primary font-label-md text-label-md transition-all shadow-md flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <Bot className="h-4 w-4" aria-hidden="true" />
                  Check AI Probability
                </button>
                {result ? (
                  <>
                    <button
                      type="button"
                      onClick={handleHumanizeAndCopy}
                      className="w-full sm:w-auto px-4 py-2.5 rounded-lg bg-surface-container-low hover:bg-surface-container text-on-surface font-label-md text-label-md transition-all border border-surface-container-highest/80 flex items-center justify-center gap-1.5 cursor-pointer"
                    >
                      {copied ? (
                        <Check className="h-4 w-4 text-primary" aria-hidden="true" />
                      ) : (
                        <Sparkles className="h-4 w-4 text-primary" aria-hidden="true" />
                      )}
                      {copied ? "Copied Clean Human Text" : "Humanize & Copy Text"}
                    </button>
                    <button
                      type="button"
                      onClick={handleDownloadReport}
                      className="w-full sm:w-auto px-4 py-2.5 rounded-lg bg-surface-container-low hover:bg-surface-container text-on-surface font-label-md text-label-md transition-all border border-surface-container-highest/80 flex items-center justify-center gap-1.5 cursor-pointer"
                    >
                      <Download className="h-4 w-4" aria-hidden="true" />
                      Download Report
                    </button>
                  </>
                ) : null}
              </div>

              <div className="flex items-center gap-4">
                <button
                  type="button"
                  onClick={handleReset}
                  disabled={!hasText && !result}
                  className="flex cursor-pointer items-center gap-1.5 font-label-md text-label-md text-secondary hover:text-error transition-colors disabled:cursor-not-allowed disabled:text-outline"
                >
                  <RotateCcw className="h-4 w-4" aria-hidden="true" />
                  Reset
                </button>

                <div className="hidden md:flex items-center gap-1.5 font-label-md text-label-md text-secondary">
                  <ShieldCheck className="h-4 w-4 text-primary" aria-hidden="true" />
                  <span>100% Client-Side</span>
                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </section>
  );
}
