export default function HowItWorks() {
  return (
    <section className="w-full py-12 md:py-16 flex flex-col space-y-space-md">
      <div className="space-y-space-xs">
        <h2 className="font-headline-lg text-headline-lg text-on-surface font-semibold">
          How it works
        </h2>
        <p className="font-body-lg text-body-lg text-on-surface-variant">
          Three steps, no configuration required.
        </p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-space-md relative">
        {/* Step 1 */}
        <div className="p-space-md rounded-xl bg-surface-container-lowest shadow-sm flex flex-col space-y-space-sm relative">
          <div className="flex items-center justify-between">
            <span className="font-code-stat text-code-stat text-primary font-bold">Step 01</span>
            <span className="material-symbols-outlined text-[20px] text-outline">content_paste</span>
          </div>
          <h3 className="font-headline-md text-headline-md text-on-surface font-semibold">Paste</h3>
          <p className="font-body-md text-body-md text-on-surface-variant leading-relaxed">
            Paste text generated by ChatGPT, Claude, Gemini, or another AI.
          </p>
        </div>
        {/* Step 2 */}
        <div className="p-space-md rounded-xl bg-surface-container-lowest shadow-sm flex flex-col space-y-space-sm relative">
          <div className="flex items-center justify-between">
            <span className="font-code-stat text-code-stat text-primary font-bold">Step 02</span>
            <span className="material-symbols-outlined text-[20px] text-outline">tune</span>
          </div>
          <h3 className="font-headline-md text-headline-md text-on-surface font-semibold">Clean</h3>
          <p className="font-body-md text-body-md text-on-surface-variant leading-relaxed">
            We remove hidden characters, formatting artifacts, and unwanted symbols.
          </p>
        </div>
        {/* Step 3 */}
        <div className="p-space-md rounded-xl bg-surface-container-lowest shadow-sm flex flex-col space-y-space-sm relative">
          <div className="flex items-center justify-between">
            <span className="font-code-stat text-code-stat text-primary font-bold">Step 03</span>
            <span className="material-symbols-outlined text-[20px] text-outline">
              assignment_turned_in
            </span>
          </div>
          <h3 className="font-headline-md text-headline-md text-on-surface font-semibold">Copy</h3>
          <p className="font-body-md text-body-md text-on-surface-variant leading-relaxed">
            Copy your clean text and use it wherever you need it.
          </p>
        </div>
      </div>
    </section>
  );
}
