import SectionHeading from "@/components/SectionHeading";

const steps = [
  {
    number: "01",
    title: "Paste",
    description:
      "Paste text generated by ChatGPT, Claude, Gemini, or another AI.",
  },
  {
    number: "02",
    title: "Clean",
    description:
      "We remove hidden characters, formatting artifacts, and unwanted symbols.",
  },
  {
    number: "03",
    title: "Copy",
    description: "Copy your clean text and use it wherever you need it.",
  },
];

export default function HowItWorks() {
  return (
    <section id="how-it-works" className="bg-neutral-50">
      <div className="container mx-auto flex flex-col gap-12 px-6 py-20">
        <SectionHeading
          title="How it works"
          subtitle="Three steps, no configuration required."
        />
        <div className="mx-auto grid w-full max-w-4xl gap-10 sm:grid-cols-3">
          {steps.map((step) => (
            <div key={step.number} className="flex flex-col gap-2">
              <p className="text-body-sm font-bold text-primary-600">
                {step.number}
              </p>
              <h4>{step.title}</h4>
              <p className="text-body-md text-neutral-700">
                {step.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
