import React from "react";
import Link from "next/link";

export interface SubToolContentProps {
  title: string;
  badgeLabel?: string;
  badgeIcon?: string;
  directAnswerTitle: string;
  directAnswerText: string;
  technicalGuidePoints?: { title: string; desc: string }[];
  beforeExample: React.ReactNode;
  afterExample: React.ReactNode;
  beforeNote?: string;
  afterNote?: string;
  beforeBadgeText?: string;
  afterBadgeText?: string;
  removedItems: { character: string; unicode: string; description: string }[];
  activeSuiteToolHref?: string;
  streamChart?: boolean;
  howToSteps: { title: string; description: string }[];
  benchmarksTitle?: string;
  benchmarks?: { name: string; time: string }[];
  valueProps?: { title: string; desc: string; icon: string }[];
  faqs: { question: string; answer: string }[];
}

const suiteTools = [
  {
    href: "/ai-text-detector",
    title: "AI Text Detector",
    desc: "Check AI score & highlight ChatGPT text with statistical burstiness flags.",
    icon: "find_in_page",
  },
  {
    href: "/remove-ai-words",
    title: "Remove AI Buzzwords",
    desc: "Strip delve, tapestry, and LLM clichés commonly generated by default models.",
    icon: "spellcheck",
  },
  {
    href: "/strip-ai-prompts",
    title: "Strip AI Prompts",
    desc: "Clean Midjourney & SD flags (--ar, --v) and prompt meta parameters.",
    icon: "terminal",
  },
  {
    href: "/visualize-invisible-characters",
    title: "Invisible Visualizer",
    desc: "Inspect zero-width spaces with inline tags and hex identity badges.",
    icon: "visibility",
  },
  {
    href: "/check-readability-score",
    title: "Readability Score",
    desc: "Calculate Flesch-Kincaid grade level, sentence complexity, and reading ease.",
    icon: "analytics",
  },
  {
    href: "/case-converter",
    title: "Case Converter",
    desc: "Convert Title Case, camelCase, snake_case, UPPERCASE, and URL slugs.",
    icon: "text_fields",
  },
  {
    href: "/clean-pdf-metadata",
    title: "PDF Metadata Cleaner",
    desc: "Purge author info, revision history, creator stamps, and embedded metadata.",
    icon: "picture_as_pdf",
  },
  {
    href: "/clean-unicode-homoglyphs",
    title: "Homoglyph Sanitizer",
    desc: "Normalize lookalike Cyrillic glyphs and mixed character sets back to pure ASCII.",
    icon: "spellcheck",
  },
];

const defaultValueProps: { title: string; desc: string; icon: string }[] = [
  {
    title: "100% In-Browser Privacy",
    desc: "Your text never travels to a remote server. Execution takes place purely in browser heap memory.",
    icon: "lock",
  },
  {
    title: "Instant Processing",
    desc: "Sub-millisecond processing speed regardless of document length with streamlined regex passes.",
    icon: "electric_bolt",
  },
  {
    title: "Advanced Heuristic Detection",
    desc: "Isolates stylistic anomalies, token-length variance, and syntactic LLM patterns automatically.",
    icon: "psychology",
  },
  {
    title: "Multi-Language Static Support",
    desc: "Engineered to accurately parse Latin, CJK, Cyrillic, and Right-to-Left bidirectional scripts without distortion.",
    icon: "public",
  },
  {
    title: "Visual Highlight Breakdown",
    desc: "See the exact unicode positions where zero-width spaces, soft hyphens, and marks were purged.",
    icon: "highlight",
  },
  {
    title: "Zero Account Required",
    desc: "No email, registration wall, credit card, or rate limiting. Open the page and begin sanitizing.",
    icon: "no_accounts",
  },
];

const defaultBenchmarks = [
  { name: "V8 Engine (Chrome / Edge / Node)", time: "1.4ms" },
  { name: "JavaScriptCore (Safari / iOS)", time: "1.8ms" },
  { name: "SpiderMonkey (Firefox)", time: "2.1ms" },
  { name: "Mobile WebKit (Android / iOS WebView)", time: "2.6ms" },
];

export default function SubToolContent({
  title,
  badgeLabel = "Technical Guide",
  badgeIcon = "lightbulb",
  directAnswerTitle,
  directAnswerText,
  technicalGuidePoints,
  beforeExample,
  afterExample,
  beforeNote,
  afterNote,
  beforeBadgeText = "ALERT",
  afterBadgeText = "PASS",
  removedItems,
  activeSuiteToolHref,
  streamChart = true,
  howToSteps,
  benchmarksTitle = "CLIENT RUNTIME BENCHMARK",
  benchmarks = defaultBenchmarks,
  valueProps: customValueProps,
  faqs,
}: SubToolContentProps) {
  const activeValueProps = customValueProps ?? defaultValueProps;
  return (
    <div className="flex flex-col w-full space-y-12 md:space-y-16">
      {/* 1. EXPLANATORY & GUIDE SECTION */}
      <section className="w-full bg-surface-container-lowest p-space-lg rounded-2xl shadow-sm border border-surface-container-highest/60">
        <div className="flex flex-col gap-space-xs mb-space-sm">
          <div className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-surface-container text-primary font-code-stat text-code-stat w-fit">
            <span className="material-symbols-outlined text-[14px]">{badgeIcon}</span>
            <span className="uppercase font-semibold">{badgeLabel}</span>
          </div>
          <h2 className="font-headline-lg text-headline-lg text-on-surface font-semibold">
            {directAnswerTitle}
          </h2>
        </div>
        <p className="font-body-lg text-body-lg text-on-surface-variant leading-relaxed mb-space-md">
          {directAnswerText}
        </p>

        {technicalGuidePoints && technicalGuidePoints.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-space-sm pt-space-xs">
            {technicalGuidePoints.map((pt, idx) => (
              <div
                key={idx}
                className="p-space-sm rounded-xl bg-surface-container-low flex flex-col gap-1 border border-surface-container-highest/60"
              >
                <span className="font-headline-sm text-headline-sm text-on-surface font-semibold">
                  {pt.title}
                </span>
                <p className="font-body-sm text-body-sm text-on-surface-variant leading-relaxed">
                  {pt.desc}
                </p>
              </div>
            ))}
          </div>
        )}
      </section>

      {/* 2. BEFORE & AFTER COMPARISON */}
      <section className="w-full flex flex-col gap-space-sm">
        <div className="flex flex-col">
          <h2 className="font-headline-lg text-headline-lg text-on-surface font-semibold">
            See the Difference Before &amp; After Cleaning
          </h2>
          <p className="font-body-md text-body-md text-on-surface-variant mt-1">
            Hidden artifacts and zero-width characters cause unexpected layout shifts, regex crashes, and AI detector flags. Here is how clean text compares.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-space-md">
          {/* Before Card */}
          <div className="bg-surface-container-lowest p-space-md rounded-xl shadow-sm flex flex-col justify-between border border-surface-container-highest">
            <div>
              <div className="flex items-center justify-between pb-space-xs mb-space-xs border-b border-surface-container-high">
                <div className="flex items-center gap-2">
                  <span className="material-symbols-outlined text-error text-[18px]">warning</span>
                  <span className="font-headline-sm text-headline-sm text-error font-medium">
                    BEFORE (Raw Text with Hidden Artifacts)
                  </span>
                </div>
                <span className="px-2 py-0.5 rounded bg-error-container text-on-error-container font-code-stat text-code-stat font-semibold">
                  {beforeBadgeText}
                </span>
              </div>
              <div className="font-body-md text-body-md text-on-surface font-mono bg-surface-container-low p-space-sm rounded-lg whitespace-pre-wrap leading-relaxed">
                {beforeExample}
              </div>
            </div>
            <div className="mt-space-sm pt-space-xs font-code-stat text-[11px] text-error flex items-center gap-1.5 border-t border-surface-container-high/60">
              <span className="material-symbols-outlined text-[14px]">cancel</span>
              <span>{beforeNote ?? "Contains: ** markdown, curly “ ”, U+2014 em dash"}</span>
            </div>
          </div>
          {/* After Card */}
          <div className="bg-surface-container-lowest p-space-md rounded-xl shadow-sm flex flex-col justify-between border border-surface-container-highest">
            <div>
              <div className="flex items-center justify-between pb-space-xs mb-space-xs border-b border-surface-container-high">
                <div className="flex items-center gap-2">
                  <span className="material-symbols-outlined text-green-600 text-[18px]">check_circle</span>
                  <span className="font-headline-sm text-headline-sm text-green-700 font-medium">
                    AFTER (Cleaned &amp; Sanitized Output)
                  </span>
                </div>
                <span className="px-2 py-0.5 rounded bg-green-100 text-green-800 font-code-stat text-code-stat font-semibold">
                  {afterBadgeText}
                </span>
              </div>
              <div className="font-body-md text-body-md text-on-surface font-mono bg-surface-container-low p-space-sm rounded-lg whitespace-pre-wrap leading-relaxed">
                {afterExample}
              </div>
            </div>
            <div className="mt-space-sm pt-space-xs font-code-stat text-[11px] text-green-700 flex items-center gap-1.5 border-t border-surface-container-high/60">
              <span className="material-symbols-outlined text-[14px]">verified</span>
              <span>{afterNote ?? "Purged: Standard UTF-8 plain text with hidden unicode removed"}</span>
            </div>
          </div>
        </div>
      </section>

      {/* 3. TECHNICAL CHARACTER & FEATURE BREAKDOWN TABLE */}
      {removedItems.length > 0 && (
        <section className="w-full bg-surface-container-lowest rounded-2xl p-space-lg shadow-sm border border-surface-container-highest/60">
          <div className="flex flex-col mb-space-md">
            <h2 className="font-headline-lg text-headline-lg text-on-surface font-semibold">
              Technical Character &amp; Feature Breakdown
            </h2>
            <p className="font-body-md text-body-md text-on-surface-variant mt-1">
              Our browser engine detects and strips non-printable unicode points, LLM clichés, and metadata streams automatically.
            </p>
          </div>
          <div className="overflow-x-auto">
            <table className="w-full text-left font-body-md text-body-md">
              <thead>
                <tr className="bg-surface-container-low text-secondary font-code-stat text-code-stat">
                  <th className="py-3 px-4 rounded-l">Character / Flag Name</th>
                  <th className="py-3 px-4">Identifier / Sample</th>
                  <th className="py-3 px-4 rounded-r">Impact &amp; Behavior</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-surface-container-low">
                {removedItems.map((item, idx) => (
                  <tr key={idx} className="hover:bg-surface-container-low/40 transition-colors">
                    <td className="py-3.5 px-4 font-medium text-on-surface">{item.character}</td>
                    <td className="py-3.5 px-4 font-code-stat text-code-stat text-primary font-semibold">{item.unicode}</td>
                    <td className="py-3.5 px-4 text-on-surface-variant font-body-sm text-body-sm leading-relaxed">{item.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>
      )}

      {/* 4. DEEP IN-BROWSER AI ANALYSIS & TELEMETRY */}
      <section className="w-full bg-surface-container-lowest rounded-2xl p-space-lg shadow-sm border border-surface-container-highest/60">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-space-lg items-center">
          <div className="lg:col-span-7 flex flex-col gap-space-md">
            <div className="space-y-space-xs">
              <span className="font-code-stat text-code-stat text-primary uppercase font-semibold">
                Deep In-Browser AI Analysis
              </span>
              <h2 className="font-headline-lg text-headline-lg text-on-surface font-semibold">
                Understand how our AI detection &amp; text sanitization engine works
              </h2>
              <p className="font-body-md text-body-md text-on-surface-variant leading-relaxed">
                Unlike cloud-based checkers that upload your documents to external databases, our detection engine analyzes sentence length variance, passive voice structure, and transition density 100% inside your browser memory. Your drafts remain confidential, safe from unauthorized data logging.
              </p>
            </div>

            {streamChart ? (
              <div className="p-3 bg-surface-container-low rounded-xl flex items-center justify-between border border-surface-container-highest/60">
                <div className="flex items-center gap-3">
                  <svg className="text-primary shrink-0" height="40" viewBox="0 0 40 40" width="40">
                    <circle cx="20" cy="20" fill="none" opacity="0.2" r="16" stroke="currentColor" strokeDasharray="100" strokeDashoffset="15" strokeWidth="3"></circle>
                    <circle cx="20" cy="20" fill="none" r="16" stroke="currentColor" strokeDasharray="100" strokeDashoffset="35" strokeWidth="3"></circle>
                  </svg>
                  <div className="flex flex-col">
                    <span className="font-headline-sm text-headline-sm text-on-surface font-medium">Zero Data Egress</span>
                    <span className="font-code-stat text-code-stat text-secondary">WebAssembly Heuristic Pipeline active</span>
                  </div>
                </div>
                <div className="font-code-stat text-code-stat bg-surface-container-high px-2.5 py-1 rounded text-primary font-bold">
                  SAFE_SANDBOX
                </div>
              </div>
            ) : (
              <div className="flex flex-wrap gap-space-xs">
                <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded bg-surface-container text-on-surface font-label-sm text-label-sm shadow-sm border border-surface-container-highest/60">
                  <span className="material-symbols-outlined text-primary text-[15px]">code_blocks</span>
                  Local Heuristic Analysis
                </span>
                <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded bg-surface-container text-on-surface font-label-sm text-label-sm shadow-sm border border-surface-container-highest/60">
                  <span className="material-symbols-outlined text-primary text-[15px]">lock</span>
                  100% Private Client Memory
                </span>
              </div>
            )}
          </div>
          {/* Right Terminal Window */}
          <div className="lg:col-span-5 w-full">
            <div className="w-full bg-inverse-surface text-inverse-on-surface rounded-xl shadow-xl overflow-hidden font-code-stat text-code-stat">
              <div className="bg-black/40 px-4 py-2.5 flex items-center justify-between border-b border-surface-variant/20">
                <div className="flex items-center gap-1.5">
                  <span className="w-2.5 h-2.5 rounded-full bg-error inline-block"></span>
                  <span className="w-2.5 h-2.5 rounded-full bg-amber-400 inline-block"></span>
                  <span className="w-2.5 h-2.5 rounded-full bg-green-500 inline-block"></span>
                  <span className="text-[11px] text-surface-dim ml-2 font-mono">bash — client-worker</span>
                </div>
                <span className="text-[10px] text-outline font-mono">sandbox://client-worker</span>
              </div>
              <div className="p-4 space-y-2 leading-relaxed text-surface-container-lowest/90 font-mono text-[12px]">
                <div className="text-primary-fixed font-bold">&gt; AI Text Sanitizer — 100% In-Browser</div>
                <div className="text-outline-variant font-normal">// Instant local inspection</div>
                <div className="flex items-center gap-2 text-green-400">
                  <span>✓</span>
                  <span>0 Invisible Characters</span>
                </div>
                <div className="flex items-center gap-2 text-green-400">
                  <span>✓</span>
                  <span>AI Buzzwords Stripped</span>
                </div>
                <div className="flex items-center gap-2 text-green-400">
                  <span>✓</span>
                  <span>94% Human Rhythm</span>
                </div>
                <div className="pt-2 text-amber-300 flex items-center gap-1.5">
                  <span className="material-symbols-outlined text-[14px]">lock</span>
                  <span>Zero server logs. Zero cloud uploads.</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 5. ALL-IN-ONE TEXT SANITIZATION SUITE */}
      <section className="w-full flex flex-col gap-space-md">
        <div className="flex flex-col">
          <div className="flex items-center gap-2">
            <span className="font-code-stat text-code-stat text-primary uppercase font-semibold">Modular Utilities</span>
          </div>
          <h2 className="font-headline-lg text-headline-lg text-on-surface font-semibold">
            All-In-One Text Sanitization Suite
          </h2>
          <p className="font-body-md text-body-md text-on-surface-variant">
            Engineered for rapid workflow automation across copywriting, publishing, engineering, and academic review.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-space-md">
          {suiteTools.map((tool, idx) => {
            const isActive = activeSuiteToolHref === tool.href;
            return (
              <Link
                key={idx}
                href={tool.href}
                className={`p-space-md rounded-xl shadow-sm transition-all flex flex-col justify-between group relative overflow-hidden ${
                  isActive
                    ? "bg-primary-container text-on-primary shadow-md ring-1 ring-primary"
                    : "bg-surface-container-lowest hover:bg-surface-container-low border border-surface-container-highest"
                }`}
              >
                {isActive && (
                  <div className="absolute top-2 right-2 px-1.5 py-0.5 rounded bg-surface-container-lowest/30 text-on-primary font-code-stat text-[10px] uppercase font-bold">
                    Active
                  </div>
                )}
                <div>
                  <div
                    className={`w-9 h-9 rounded-lg flex items-center justify-center mb-space-sm group-hover:scale-105 transition-transform ${
                      isActive
                        ? "bg-surface-container-lowest/20 text-on-primary shadow-sm"
                        : "bg-surface-container text-primary"
                    }`}
                  >
                    <span className="material-symbols-outlined text-[20px]">{tool.icon}</span>
                  </div>
                  <h3
                    className={`font-headline-sm text-headline-sm font-semibold mb-1 transition-colors ${
                      isActive ? "text-on-primary" : "text-on-surface group-hover:text-primary"
                    }`}
                  >
                    {tool.title}
                  </h3>
                  <p
                    className={`font-body-sm text-body-sm leading-relaxed ${
                      isActive ? "text-on-primary-container" : "text-on-surface-variant"
                    }`}
                  >
                    {tool.desc}
                  </p>
                </div>
                <span
                  className={`font-code-stat text-code-stat mt-3 flex items-center gap-1 ${
                    isActive ? "text-on-primary-container font-semibold" : "text-primary"
                  }`}
                >
                  {isActive ? "Current Module" : "Launch Tool →"}
                </span>
              </Link>
            );
          })}
        </div>
      </section>

      {/* 6. HOW-TO PROCESS (3 SIMPLE STEPS) */}
      <section className="w-full flex flex-col gap-space-md">
        <div className="flex flex-col">
          <span className="font-code-stat text-code-stat text-primary uppercase font-semibold">Workflow Process</span>
          <h2 className="font-headline-lg text-headline-lg text-on-surface font-semibold">
            3 Simple Steps to Use {title}
          </h2>
          <p className="font-body-md text-body-md text-on-surface-variant">
            No software installation, account registration, or cloud API keys required. Processed entirely inside your local browser.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-space-md">
          {howToSteps.map((step, idx) => (
            <div
              key={idx}
              className="p-space-md rounded-xl bg-surface-container-lowest border border-surface-container-highest shadow-sm flex flex-col justify-between space-y-space-sm hover:shadow-md hover:border-primary/40 transition-all"
            >
              <div className="space-y-space-xs">
                <div className="w-8 h-8 rounded-lg bg-primary-fixed/40 text-primary flex items-center justify-center font-code-stat font-bold text-sm">
                  0{idx + 1}
                </div>
                <h3 className="font-headline-sm text-headline-sm font-semibold text-on-surface">
                  {step.title}
                </h3>
                <p className="font-body-sm text-body-sm text-secondary leading-relaxed">
                  {step.description}
                </p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* 7. MOBILE & DESKTOP READY FEATURE CALLOUT */}
      <section className="w-full grid grid-cols-1 lg:grid-cols-12 gap-space-lg items-center bg-surface-container-lowest p-space-lg rounded-2xl shadow-sm border border-surface-container-highest/60">
        <div className="lg:col-span-7 space-y-space-md">
          <div className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded bg-surface-container text-primary font-code-stat text-code-stat font-semibold">
            <span className="material-symbols-outlined text-[14px]">devices</span>
            <span>ZERO-INSTALL UTILITY</span>
          </div>
          <h2 className="font-headline-lg text-headline-lg text-on-surface font-semibold">
            Clean and check AI content anywhere — 100% Client-Side Privacy
          </h2>
          <p className="font-body-lg text-body-lg text-on-surface-variant leading-relaxed">
            Whether you are drafting articles on mobile, writing academic papers on laptop, or sanitizing code comments, our browser engine runs locally with zero installation and zero cloud data retention.
          </p>
          <ul className="space-y-2 font-body-md text-body-md text-on-surface">
            <li className="flex items-center gap-2">
              <span className="material-symbols-outlined text-primary text-[18px]">check_circle</span>
              <span>Instant local processing — no network latency or queues</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="material-symbols-outlined text-primary text-[18px]">check_circle</span>
              <span>Zero server storage — your content never leaves your device</span>
            </li>
            <li className="flex items-center gap-2">
              <span className="material-symbols-outlined text-primary text-[18px]">check_circle</span>
              <span>Compatible with all modern web browsers &amp; mobile devices</span>
            </li>
          </ul>
        </div>
        <div className="lg:col-span-5 flex justify-center w-full">
          <div className="w-full max-w-sm bg-surface-container-low p-space-md rounded-xl space-y-3 border border-surface-container-highest">
            <div className="flex items-center justify-between font-code-stat text-code-stat text-secondary pb-2 border-b border-surface-container-highest">
              <span>{benchmarksTitle}</span>
              <span className="text-primary font-semibold">ZERO-LATENCY</span>
            </div>
            <p className="font-code-stat text-[10px] text-outline">
              Measured on standard 10,000-character test payloads across modern desktop &amp; mobile engines.
            </p>
            <div className="space-y-2 font-label-sm text-label-sm">
              {benchmarks.map((bm, bIdx) => (
                <div key={bIdx} className="flex justify-between items-center p-2 rounded bg-surface-container-lowest">
                  <span className="text-on-surface">{bm.name}</span>
                  <span className="text-emerald-600 font-semibold">{bm.time}</span>
                </div>
              ))}
            </div>
            <div className="pt-2 text-[10px] font-code-stat text-emerald-700 flex items-center gap-1 border-t border-surface-container-highest">
              <span className="material-symbols-outlined text-[13px]">verified</span>
              <span>100% Local In-Memory UTF-8 Pipeline</span>
            </div>
          </div>
        </div>
      </section>

      {/* 8. WHY CHOOSE AI TEXT CLEANER (VALUE PROPS) */}
      <section className="w-full flex flex-col gap-space-md">
        <div className="flex flex-col">
          <span className="font-code-stat text-code-stat text-primary uppercase font-semibold">Architectural Principles</span>
          <h2 className="font-headline-lg text-headline-lg text-on-surface font-semibold">
            Why Choose Text Cleaner AI
          </h2>
          <p className="font-body-md text-body-md text-on-surface-variant">
            Engineered without compromises on security, fidelity, or execution overhead.
          </p>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-space-md">
          {activeValueProps.map((val, idx) => (
            <div
              key={idx}
              className="p-space-md rounded-xl bg-surface-container-lowest border border-surface-container-highest shadow-sm space-y-space-xs hover:shadow-md hover:border-primary/40 transition-all flex flex-col gap-2"
            >
              <div className="w-8 h-8 rounded-lg bg-surface-container flex items-center justify-center text-primary">
                <span className="material-symbols-outlined text-[20px]">{val.icon}</span>
              </div>
              <h3 className="font-headline-sm text-headline-sm font-semibold text-on-surface">
                {val.title}
              </h3>
              <p className="font-body-md text-body-md text-on-surface-variant leading-relaxed">
                {val.desc}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* 9. FAQ SECTION */}
      {faqs.length > 0 && (
        <section className="w-full bg-surface-container-lowest rounded-2xl p-space-lg shadow-sm border border-surface-container-highest/60">
          <div className="flex flex-col mb-space-md">
            <span className="font-code-stat text-code-stat text-primary uppercase font-semibold">Knowledge Base</span>
            <h2 className="font-headline-lg text-headline-lg text-on-surface font-semibold">
              Your questions, answered
            </h2>
          </div>
          <div className="space-y-3 w-full">
            {faqs.map((faq, idx) => (
              <details
                key={idx}
                className="group bg-surface-container-low rounded-xl p-4 transition-all [&_summary::-webkit-details-marker]:hidden border border-transparent hover:border-surface-container-highest"
              >
                <summary className="flex items-center justify-between cursor-pointer font-headline-sm text-headline-sm font-semibold text-on-surface select-none">
                  <span>{faq.question}</span>
                  <span className="material-symbols-outlined text-[20px] text-secondary transition-transform duration-200 group-open:rotate-180">
                    expand_more
                  </span>
                </summary>
                <p className="font-body-md text-body-md text-on-surface-variant mt-2 leading-relaxed">
                  {faq.answer}
                </p>
              </details>
            ))}
          </div>
        </section>
      )}
    </div>
  );
}
