import type { Metadata } from "next";
import Hero from "@/components/Hero";
import SubToolContent from "@/components/SubToolContent";

const siteUrl = "https://aitextcleaner.com";

export const metadata: Metadata = {
  title: "Clean Claude Text — Remove Anthropic Claude Formatting & Artifacts",
  description:
    "Clean text copied from Anthropic Claude 3.5 Sonnet & Opus. Remove unwanted Markdown tags, bold asterisks, smart quotes, and zero-width spaces.",
  keywords: [
    "clean claude text",
    "clean anthropic claude output",
    "remove claude formatting",
    "claude text sanitizer",
    "clean claude markdown",
  ],
  alternates: {
    canonical: "/clean-claude-text",
  },
  openGraph: {
    title: "Clean Claude Text — Remove Anthropic Claude Formatting & Artifacts",
    description:
      "Paste your Anthropic Claude responses to instantly strip unwanted markdown formatting and hidden unicode artifacts.",
    url: `${siteUrl}/clean-claude-text`,
  },
};

const removedItems = [
  {
    character: "Claude Code Block Backticks",
    unicode: "U+0060 (`)",
    description: "Anthropic Claude outputs code and text artifacts in backtick blocks that need to be stripped for plain text.",
  },
  {
    character: "Smart Quotes & Typography",
    unicode: "U+201C / U+201D",
    description: "Curly quotes inserted by Claude that cause formatting glitches when pasted into Google Docs or CMS editors.",
  },
  {
    character: "Invisible Unicode Spacers",
    unicode: "U+200B / U+00A0",
    description: "Hidden non-breaking spaces and zero-width spaces generated between rendered response paragraphs.",
  },
];

const howToSteps = [
  {
    title: "Copy from Claude.ai",
    description: "Copy your text response or generated article directly from the Anthropic Claude interface.",
  },
  {
    title: "Paste into Cleaner",
    description: "Paste into the editor above. Our engine applies optimal Claude text sanitization presets.",
  },
  {
    title: "Copy Clean Plain Text",
    description: "Click Clean Text to get publication-ready plain text with zero formatting quirks.",
  },
];

const faqs = [
  {
    question: "Why does text copied from Claude have extra formatting?",
    answer:
      "Claude formats text using Markdown (headers, bullet points, asterisks) and rich web styling. When copied into documents or email, raw Markdown tags and non-breaking spaces often remain behind.",
  },
  {
    question: "Is my Claude text data kept private?",
    answer:
      "Yes. All cleaning operations happen 100% locally inside your browser JavaScript runtime. No text is sent to cloud servers.",
  },
  {
    question: "Does this work with Claude 3.5 Sonnet and Claude 3 Opus?",
    answer:
      "Yes! It sanitizes output generated by all models in the Anthropic Claude family, including Claude 3.5 Sonnet, Claude 3 Opus, and Claude 3 Haiku.",
  },
  {
    question: "How do I remove backticks (`code`) from Claude outputs?",
    answer:
      "Check the 'Remove markdown formatting' box. Our engine automatically removes surrounding code backticks while leaving your inner text intact.",
  },
  {
    question: "Can I remove overused AI buzzwords from Claude writing?",
    answer:
      "Yes! Enable the 'Remove AI buzzwords' filter to automatically strip repetitive terms like 'delve', 'tapestry', and 'testament' from Claude's response.",
  },
];

const webAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "Claude Text Cleaner",
  url: `${siteUrl}/clean-claude-text`,
  description: "Free tool to sanitize text copied from Anthropic Claude AI.",
  applicationCategory: "UtilitiesApplication",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
};

const howToJsonLd = {
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to Clean Claude AI Text Formatting",
  step: howToSteps.map((step) => ({
    "@type": "HowToStep",
    name: step.title,
    text: step.description,
  })),
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
};

export default function CleanClaudeTextPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <Hero
        heading="Clean Claude AI Text"
        subheading="Sanitize text from Anthropic Claude. Remove unwanted Markdown symbols, asterisks, smart quotes, and zero-width spaces instantly."
        initialOptions={{
          removeMarkdown: true,
          normalizeQuotes: true,
          normalizeDashes: true,
          removeTrailingWhitespace: true,
          removeHiddenCharacters: true,
        }}
      />
      <SubToolContent
        title="Clean Claude Text"
        directAnswerTitle="How to Clean Anthropic Claude Text Output?"
        directAnswerText="Anthropic Claude produces eloquent text, but copying output into external documents introduces raw Markdown asterisks, smart quotes, and non-breaking spaces. Our tool strips these formatting artifacts instantly in your browser, leaving clean plain text."
        beforeExample={"**Claude Summary:**\n- Here is a point with *italic* words.\n- “Smart quotes” & — em dashes."}
        afterExample={'Claude Summary:\n- Here is a point with italic words.\n- "Smart quotes" & - em dashes.'}
        removedItems={removedItems}
        howToSteps={howToSteps}
        faqs={faqs}
      />
    </>
  );
}
