import type { Metadata } from "next";
import HumanizeTextUI from "@/components/HumanizeTextUI";
import SubToolContent from "@/components/SubToolContent";
import { generateSubToolMetadata } from "@/components/LocalizedSubToolLayout";
import { LANGUAGES } from "@/lib/i18n/dictionaries";

export const dynamic = "force-static";

export function generateStaticParams() {
  return Object.keys(LANGUAGES)
    .filter((code) => code !== "en")
    .map((lang) => ({ lang }));
}

export async function generateMetadata({ params }: { params: Promise<{ lang: string }> }): Promise<Metadata> {
  const { lang } = await params;
  return generateSubToolMetadata(lang, "humanizeAIText", "humanize-ai-text");
}

const removedItems = [
  {
    character: "AI Buzzword: 'delve'",
    unicode: "Delve into...",
    description: "Overused LLM cliché replaced with direct verbs ('explore', 'examine', or removed).",
  },
  {
    character: "AI Cliché: 'vibrant tapestry'",
    unicode: "Tapestry of...",
    description: "Robotic AI metaphor replaced with concrete noun descriptors ('rich variety', 'combination').",
  },
  {
    character: "Transition: 'Furthermore / In conclusion'",
    unicode: "Furthermore,",
    description: "Monotonous transition starters simplified to active conversational prose.",
  },
  {
    character: "AI Phrase: 'testament to'",
    unicode: "Serves as a testament to...",
    description: "Redundant fluff phrase simplified to direct active voice ('shows', 'demonstrates').",
  },
];

const howToSteps = [
  {
    title: "Paste AI Draft",
    description: "Paste text generated by ChatGPT, Claude, Gemini, or Copilot.",
  },
  {
    title: "Detect Clichés & Pattern Score",
    description: "Our analyzer scans transition density, overused vocabulary, and structural monotony.",
  },
  {
    title: "Copy Humanized Output",
    description: "Copy polished text with natural sentence length variation and zero robotic buzzwords.",
  },
];

const faqs = [
  {
    question: "Will this help me get past an AI detector?",
    answer:
      "Not reliably, and that's not really the goal. This tool is meant to make writing read more naturally — shorter, more varied sentences and fewer clichés. Detectors weigh many signals, and no tool can guarantee a specific result.",
  },
  {
    question: "Does it change what the text says?",
    answer: "No. It edits phrasing and rhythm, not the substance of your writing.",
  },
];

export default async function LocalizedHumanizeAITextPage({ params }: { params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  const l = LANGUAGES[lang] || LANGUAGES.en;
  const isRtl = l.dir === "rtl";
  const tool = l.subtools?.humanizeAIText || LANGUAGES.en.subtools.humanizeAIText!;

  return (
    <div dir={isRtl ? "rtl" : "ltr"} className={isRtl ? "font-arabic" : ""}>
      <HumanizeTextUI
        heading={tool.heading}
        subheading={tool.subheading}
      />
      <div className="container mx-auto px-4 md:px-8 pb-16">
        <SubToolContent
          title={tool.heading}
          badgeLabel="Heuristic Normalizer"
          badgeIcon="auto_fix"
          directAnswerTitle={tool.heading}
          directAnswerText={tool.subheading}
          beforeBadgeText="BEFORE: Raw AI Text"
          afterBadgeText="AFTER: Cleaned & Sanitized"
          beforeExample="In conclusion, it is important to note that artificial intelligence serves as a testament to human innovation. Furthermore, delving into this digital realm allows us to foster pivotal advancements."
          afterExample="Artificial intelligence shows human innovation. Exploring this field drives key advancements."
          beforeNote="Flat rhythm, repeated transitions, overused AI phrases"
          afterNote="Varied sentence length, plainer phrasing, same meaning"
          removedItems={removedItems}
          howToSteps={howToSteps}
          faqs={faqs}
        />
      </div>
    </div>
  );
}
