import type { Metadata } from "next";
import HumanizeTextUI from "@/components/HumanizeTextUI";
import SubToolContent from "@/components/SubToolContent";

const siteUrl = "https://www.text-cleaner-ai.com";

export const metadata: Metadata = {
  title: "Humanize AI Text — Remove Clichés and Vary Sentence Rhythm",
  description:
    "Make AI-written text read more naturally. Remove overused phrases like \"delve\" and \"tapestry\" and vary sentence length. Free, browser-based.",
  keywords: [
    "humanize ai text",
  ],
  alternates: {
    canonical: "/humanize-ai-text",
  },
  openGraph: {
    title: "Humanize AI Text — Remove Clichés and Vary Sentence Rhythm",
    description:
      "Remove overused AI phrases and vary sentence rhythm so writing reads more naturally.",
    url: `${siteUrl}/humanize-ai-text`,
  },
};

const removedItems = [
  {
    character: "AI Buzzword: 'delve'",
    unicode: "Delve into...",
    description: "Overused LLM cliché replaced with direct verbs ('explore', 'examine', or removed).",
  },
  {
    character: "AI Cliché: 'vibrant tapestry'",
    unicode: "Tapestry of...",
    description: "Robotic AI metaphor replaced with concrete noun descriptors ('rich variety', 'combination').",
  },
  {
    character: "Transition: 'Furthermore / In conclusion'",
    unicode: "Furthermore,",
    description: "Monotonous transition starters simplified to active conversational prose.",
  },
  {
    character: "AI Phrase: 'testament to'",
    unicode: "Serves as a testament to...",
    description: "Redundant fluff phrase simplified to direct active voice ('shows', 'demonstrates').",
  },
];

const howToSteps = [
  {
    title: "Paste AI Draft",
    description: "Paste text generated by ChatGPT, Claude, Gemini, or Copilot.",
  },
  {
    title: "Detect Clichés & Pattern Score",
    description: "Our analyzer scans transition density, overused vocabulary, and structural monotony.",
  },
  {
    title: "Copy Humanized Output",
    description: "Copy polished text with natural sentence length variation and zero robotic buzzwords.",
  },
];

const faqs = [
  {
    question: "Will this help me get past an AI detector?",
    answer:
      "Not reliably, and that's not really the goal. This tool is meant to make writing read more naturally — shorter, more varied sentences and fewer clichés. Detectors weigh many signals, and no tool can guarantee a specific result.",
  },
  {
    question: "Does it change what the text says?",
    answer: "No. It edits phrasing and rhythm, not the substance of your writing.",
  },
];

const webAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "AI Text Humanizer",
  url: `${siteUrl}/humanize-ai-text`,
  description: "Remove overused AI phrases and vary sentence rhythm so writing reads more naturally.",
  applicationCategory: "UtilitiesApplication",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
};

const howToJsonLd = {
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to Humanize AI Text Online",
  step: howToSteps.map((step) => ({
    "@type": "HowToStep",
    name: step.title,
    text: step.description,
  })),
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
};

const benchmarks = [
  { name: "Google Chrome", time: "Instant" },
  { name: "Apple Safari", time: "Instant" },
  { name: "Mozilla Firefox", time: "Instant" },
];

export default function HumanizeAITextPage() {
  return (
    <div className="w-full flex flex-col">
      <span className="sr-only">
        Humanize AI Text Online | Text Cleaner AI
      </span>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <HumanizeTextUI
        heading="Humanize AI Text"
        subheading="Remove overused phrases and vary sentence rhythm so AI-written text reads more naturally. Free, browser-based."
      />
      <div className="container mx-auto px-4 md:px-8 pb-16">
        <SubToolContent
          title="Humanize AI Text"
          badgeLabel="Heuristic Normalizer"
          badgeIcon="auto_fix"
          directAnswerTitle="Why AI Writing Has a Flat Rhythm"
          directAnswerText="AI writing tends to have a flat rhythm — sentences land at a similar length, the same handful of transition words show up again and again, and certain words (delve, tapestry, testament, elevate) appear far more than a person would naturally use them. This tool edits for that rhythm: it removes the overused words, breaks up repetitive sentence patterns, and tightens transitions like &quot;furthermore&quot; and &quot;in conclusion&quot; into something closer to how people actually write."
          beforeBadgeText="BEFORE: Raw AI Text"
          afterBadgeText="AFTER: Cleaned & Sanitized"
          beforeExample={
            <p className="font-body-md text-body-md text-on-surface-variant leading-loose">
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                In conclusion,
              </span>{" "}
              it is important to note that artificial intelligence{" "}
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                serves as a testament to
              </span>{" "}
              human innovation.{" "}
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                Furthermore,
              </span>{" "}
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                delving into
              </span>{" "}
              this{" "}
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                digital realm
              </span>{" "}
              allows us to foster{" "}
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                pivotal advancements
              </span>
              .
            </p>
          }
          afterExample={
            <p className="font-body-md text-body-md text-on-surface leading-loose">
              Artificial intelligence shows human innovation. Exploring this field drives key advancements.
            </p>
          }
          beforeNote="Flat rhythm, repeated transitions, overused AI phrases"
          afterNote="Varied sentence length, plainer phrasing, same meaning"
          streamChart={true}
          benchmarksTitle="Heuristic Engine Latency"
          benchmarks={benchmarks}
          removedItems={removedItems}
          howToSteps={howToSteps}
          faqs={faqs}
        />
      </div>
    </div>
  );
}
