import type { Metadata } from "next";
import HumanizeTextUI from "@/components/HumanizeTextUI";
import SubToolContent from "@/components/SubToolContent";

const siteUrl = "https://www.text-cleaner-ai.com";

export const metadata: Metadata = {
  title: "Humanize AI Text Online — Remove AI Clichés & Fix Sentence Rhythm",
  description:
    "Free online AI text humanizer. Remove robotic buzzwords (delve, tapestry, realm), simplify passive transition phrases, and optimize natural human sentence flow.",
  keywords: [
    "humanize ai text",
    "remove ai buzzwords",
    "delve tapestry realm remover",
    "make ai text sound human",
    "ai text rhythm optimizer",
  ],
  alternates: {
    canonical: "/humanize-ai-text",
  },
  openGraph: {
    title: "Humanize AI Text Online — Remove AI Clichés & Fix Sentence Rhythm",
    description:
      "Detect and strip repetitive AI transitions and cliché phrases like 'delve into', 'tapestry', and 'testament to' for natural human flow.",
    url: `${siteUrl}/humanize-ai-text`,
  },
};

const removedItems = [
  {
    character: "AI Buzzword: 'delve'",
    unicode: "Delve into...",
    description: "Overused LLM cliché replaced with direct verbs ('explore', 'examine', or removed).",
  },
  {
    character: "AI Cliché: 'vibrant tapestry'",
    unicode: "Tapestry of...",
    description: "Robotic AI metaphor replaced with concrete noun descriptors ('rich variety', 'combination').",
  },
  {
    character: "Transition: 'Furthermore / In conclusion'",
    unicode: "Furthermore,",
    description: "Monotonous transition starters simplified to active conversational prose.",
  },
  {
    character: "AI Phrase: 'testament to'",
    unicode: "Serves as a testament to...",
    description: "Redundant fluff phrase simplified to direct active voice ('shows', 'demonstrates').",
  },
];

const howToSteps = [
  {
    title: "Paste AI Draft",
    description: "Paste text generated by ChatGPT, Claude, Gemini, or Copilot.",
  },
  {
    title: "Detect Clichés & Pattern Score",
    description: "Our analyzer scans transition density, overused vocabulary, and structural monotony.",
  },
  {
    title: "Copy Humanized Output",
    description: "Copy polished text with natural sentence length variation and zero robotic buzzwords.",
  },
];

const faqs = [
  {
    question: "What does 'Humanize AI Text' mean?",
    answer:
      "Humanizing AI text means removing robotic structural quirks, overused transition words (furthermore, moreover, in conclusion), and cliché metaphors (delve, tapestry, realm, testament to) to restore clear, natural human writing.",
  },
  {
    question: "Does this tool alter the core meaning of my content?",
    answer:
      "No. It preserves your exact message, facts, and intent while stripping artificial filler phrases and passive voice.",
  },
  {
    question: "Why do AI tools use words like 'delve' and 'tapestry' so frequently?",
    answer:
      "Large language models (LLMs) are trained on RLHF datasets where certain formal transitions and expansive metaphors score high probability, causing them to repeat these specific words.",
  },
  {
    question: "Is this humanizer free and client-side?",
    answer:
      "Yes! 100% free and private. Pattern detection and humanization run completely inside your local browser memory.",
  },
];

const webAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "AI Text Humanizer",
  url: `${siteUrl}/humanize-ai-text`,
  description: "Free online tool to remove AI buzzwords and optimize natural human sentence flow.",
  applicationCategory: "UtilitiesApplication",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
};

const howToJsonLd = {
  "@context": "https://schema.org",
  "@type": "HowTo",
  name: "How to Humanize AI Text Online",
  step: howToSteps.map((step) => ({
    "@type": "HowToStep",
    name: step.title,
    text: step.description,
  })),
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
};

const benchmarks = [
  { name: "Google Chrome", time: "0.4 ms" },
  { name: "Apple Safari", time: "0.6 ms" },
  { name: "Mozilla Firefox", time: "0.7 ms" },
];

export default function HumanizeAITextPage() {
  return (
    <div className="w-full flex flex-col">
      <span className="sr-only">
        Humanize AI Text Online | Text Cleaner AI
      </span>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(howToJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <HumanizeTextUI
        heading="Humanize AI Text Online"
        subheading="Detect and remove repetitive AI transitions, robotic clichés (delve, tapestry, realm), and monotonous sentence structures for natural human flow."
      />
      <div className="container mx-auto px-4 md:px-8 pb-16">
        <SubToolContent
          title="Humanize AI Text Online"
          badgeLabel="Heuristic Normalizer"
          badgeIcon="auto_fix"
          directAnswerTitle="How to Humanize AI Text Without Losing Original Meaning"
          directAnswerText="AI text generators rely on statistical word patterns that create telltale markers: monotonous sentence lengths, passive voice constructions ('serves as a testament to'), and overused buzzwords ('delve into', 'vibrant tapestry', 'pivotal realm'). Our AI Text Humanizer strips these fluff patterns and optimizes your text for authentic human readability."
          beforeBadgeText="BEFORE: Raw AI Text"
          afterBadgeText="AFTER: Cleaned & Sanitized"
          beforeExample={
            <p className="font-body-md text-body-md text-on-surface-variant leading-loose">
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                In conclusion,
              </span>{" "}
              it is important to note that artificial intelligence{" "}
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                serves as a testament to
              </span>{" "}
              human innovation.{" "}
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                Furthermore,
              </span>{" "}
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                delving into
              </span>{" "}
              this{" "}
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                digital realm
              </span>{" "}
              allows us to foster{" "}
              <span className="bg-error-container text-on-error-container px-1 py-0.5 rounded font-medium">
                pivotal advancements
              </span>
              .
            </p>
          }
          afterExample={
            <p className="font-body-md text-body-md text-on-surface leading-loose">
              Artificial intelligence shows human innovation. Exploring this field drives key advancements.
            </p>
          }
          beforeNote="Flagged by standard entropy and perplexity classifiers."
          afterNote="Concise, zero buzzwords, active verb structure preserved."
          streamChart={true}
          benchmarksTitle="Heuristic Engine Latency"
          benchmarks={benchmarks}
          removedItems={removedItems}
          howToSteps={howToSteps}
          faqs={faqs}
        />
      </div>
    </div>
  );
}
