import type { Metadata } from "next";
import HumanizeTextUI from "@/components/HumanizeTextUI";
import SubToolContent from "@/components/SubToolContent";

const siteUrl = "https://www.text-cleaner-ai.com";

export const metadata: Metadata = {
  title: "Humanize AI Text Online — Remove AI Clichés & Fix Sentence Rhythm",
  description:
    "Free online AI text humanizer. Remove robotic buzzwords (delve, tapestry, realm), simplify passive transition phrases, and optimize natural human sentence flow.",
  keywords: [
    "humanize ai text",
    "remove ai buzzwords",
    "delve tapestry realm remover",
    "make ai text sound human",
    "ai text rhythm optimizer",
  ],
  alternates: {
    canonical: "/humanize-ai-text",
  },
  openGraph: {
    title: "Humanize AI Text Online — Remove AI Buzzwords & Improve Rhythm",
    description:
      "Detect and strip repetitive AI transitions and cliché phrases like 'delve into', 'tapestry', and 'testament to' for natural human flow.",
    url: `${siteUrl}/humanize-ai-text`,
  },
};

const removedItems = [
  {
    character: "AI Buzzword: 'delve'",
    unicode: "Delve into...",
    description: "Overused LLM cliché replaced with direct verbs ('explore', 'examine', or removed).",
  },
  {
    character: "AI Cliché: 'vibrant tapestry'",
    unicode: "Tapestry of...",
    description: "Robotic AI metaphor replaced with concrete noun descriptors ('rich variety', 'combination').",
  },
  {
    character: "Transition: 'Furthermore / In conclusion'",
    unicode: "Furthermore,",
    description: "Monotonous transition starters simplified to active conversational prose.",
  },
  {
    character: "AI Phrase: 'testament to'",
    unicode: "Serves as a testament to...",
    description: "Redundant fluff phrase simplified to direct active voice ('shows', 'demonstrates').",
  },
];

const howToSteps = [
  {
    title: "Paste AI Draft",
    description: "Paste text generated by ChatGPT, Claude, Gemini, or Copilot.",
  },
  {
    title: "Detect Clichés & Pattern Score",
    description: "Our analyzer scans transition density, overused vocabulary, and structural monotony.",
  },
  {
    title: "Copy Humanized Output",
    description: "Copy polished text with natural sentence length variation and zero robotic buzzwords.",
  },
];

const faqs = [
  {
    question: "What does 'Humanize AI Text' mean?",
    answer:
      "Humanizing AI text means removing robotic structural quirks, overused transition words (furthermore, moreover, in conclusion), and cliché metaphors (delve, tapestry, realm, testament to) to restore clear, natural human writing.",
  },
  {
    question: "Does this tool alter the core meaning of my content?",
    answer:
      "No. It preserves your exact message, facts, and intent while stripping artificial filler phrases and passive voice.",
  },
  {
    question: "Why do AI tools use words like 'delve' and 'tapestry' so frequently?",
    answer:
      "Large language models (LLMs) are trained on RLHF datasets where certain formal transitions and expansive metaphors score high probability, causing them to repeat these specific words.",
  },
  {
    question: "Is this humanizer free and client-side?",
    answer:
      "Yes! 100% free and private. Pattern detection and humanization run completely inside your local browser memory.",
  },
];

const webAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "AI Text Humanizer",
  url: `${siteUrl}/humanize-ai-text`,
  description: "Free online tool to remove AI buzzwords and optimize natural human sentence flow.",
  applicationCategory: "UtilitiesApplication",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
};

export default function HumanizeAITextPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <HumanizeTextUI
        heading="AI Text Humanizer & Structure Optimizer"
        subheading="Detect and remove repetitive AI transitions, robotic clichés (delve, tapestry, realm), and monotonous sentence structures for natural human flow."
      />
      <SubToolContent
        title="AI Text Humanizer & Structure Optimizer"
        directAnswerTitle="How to Humanize AI Text Without Losing Original Meaning"
        directAnswerText="AI text generators rely on statistical word patterns that create telltale markers: monotonous sentence lengths, passive voice constructions ('serves as a testament to'), and overused buzzwords ('delve into', 'vibrant tapestry', 'pivotal realm'). Our AI Text Humanizer strips these fluff patterns and optimizes your text for authentic human readability."
        beforeExample="In conclusion, it is important to note that artificial intelligence serves as a testament to human innovation. Furthermore, delving into this digital realm allows us to foster pivotal advancements."
        afterExample="Artificial intelligence shows human innovation. Exploring this field drives key advancements."
        removedItems={removedItems}
        howToSteps={howToSteps}
        faqs={faqs}
      />
    </>
  );
}
