import type { Metadata } from "next";
import AIDetectorUI from "@/components/AIDetectorUI";
import SubToolContent from "@/components/SubToolContent";

const siteUrl = "https://www.text-cleaner-ai.com";

export const metadata: Metadata = {
  title: "Free AI Text Detector — Check If Text Reads Like It Was AI-Written",
  description:
    "Check text for common signs of AI writing — repeated sentence patterns, overused phrases, low variation. Free, and nothing is uploaded to a server.",
  keywords: [
    "ai text detector",
    "ai text check",
  ],
  alternates: {
    canonical: "/ai-text-detector",
  },
  openGraph: {
    title: "Free AI Text Detector — Check If Text Reads Like It Was AI-Written",
    description:
      "Check text for common signs of AI writing, entirely in your browser.",
    url: `${siteUrl}/ai-text-detector`,
  },
};

const removedItems = [
  {
    character: "Sentence Length Variation",
    unicode: "Burstiness",
    description: "How much sentence length varies across the text — a flat, even rhythm is one common sign of AI writing.",
  },
  {
    character: "Common AI Transition Phrases",
    unicode: "furthermore, in conclusion",
    description: "Words like \"furthermore,\" \"in conclusion,\" and \"it's worth noting\" show up more often in AI text.",
  },
  {
    character: "Repetition in Sentence Structure",
    unicode: "n/a",
    description: "Sentences that follow the same shape and length repeatedly.",
  },
  {
    character: "Overall Predictability",
    unicode: "n/a",
    description: "How closely the writing follows the most statistically likely word choices.",
  },
];

const howToSteps = [
  {
    title: "Paste Draft Text",
    description: "Paste content generated by ChatGPT, Claude, Gemini, or Copilot into the raw text input.",
  },
  {
    title: "Check AI Probability",
    description: "Our browser engine scores sentence-length burstiness, cliché phrase density, and passive voice live.",
  },
  {
    title: "Inspect Highlights & Humanize",
    description: "Review color-coded sentence badges and click 'Humanize & Copy' to sanitize your writing.",
  },
];

const faqs = [
  {
    question: "How accurate is this?",
    answer:
      "No AI detector is fully accurate, and this one is no exception. Use it as a starting point, not proof.",
  },
  {
    question: "Does it store the text I check?",
    answer: "No. Everything runs in your browser.",
  },
  {
    question: "Can this get a human falsely flagged as AI?",
    answer:
      "Yes, that can happen with any AI detector. That's exactly why the score should be treated as a hint, not a fact.",
  },
];

const webAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "AI Text Detector",
  url: `${siteUrl}/ai-text-detector`,
  description: "Check text for common signs of AI writing, entirely in your browser.",
  applicationCategory: "UtilitiesApplication",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
};

export default function AITextDetectorPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <AIDetectorUI
        heading="AI Text Detector"
        subheading="Check text for common signs of AI writing — sentence variation, overused phrases, predictability. Free, nothing uploaded."
      />
      <SubToolContent
        title="AI Text Detector"
        directAnswerTitle="What This Tool Checks — and Its Limits"
        directAnswerText="This tool looks at a few common signs of AI-written text — how much sentence length varies, how often certain transition words appear, and how predictable the structure is — and gives you a rough read on how &quot;AI-like&quot; a piece of text looks. It's worth being upfront about the limits here: no AI detector, including this one, can prove with certainty whether a human or an AI wrote something. Detection tools produce false positives on human writing fairly often, especially for non-native English writers and for anyone with a plain, direct style. Treat the result as one signal among several, not a verdict — and don't use it to accuse someone of dishonesty based on a score alone."
        beforeExample="In today's fast-paced world, artificial intelligence serves as a testament to human innovation. Furthermore, delving into this digital realm allows us to foster pivotal advancements."
        afterExample="Flagged: low sentence-length variation, 3 common AI transition phrases"
        removedItems={removedItems}
        howToSteps={howToSteps}
        faqs={faqs}
      />
    </>
  );
}
