import type { Metadata } from "next";
import AIDetectorUI from "@/components/AIDetectorUI";
import SubToolContent from "@/components/SubToolContent";

const siteUrl = "https://www.text-cleaner-ai.com";

export const metadata: Metadata = {
  title: "Free AI Text Detector (ChatGPT, GPT-4, Claude & Gemini) — 100% In-Browser",
  description:
    "Free online AI text detector. Check if text was written by ChatGPT, Claude, GPT-4, or Gemini. Highlight overused clichés, sentence monotony, and passive-voice patterns.",
  keywords: [
    "free ai text detector",
    "chatgpt detector online",
    "gpt 4 text checker",
    "check ai generated text",
    "highlight ai phrases online",
  ],
  alternates: {
    canonical: "/ai-text-detector",
  },
  openGraph: {
    title: "Free AI Text Detector — ChatGPT, Claude & Gemini Checker",
    description:
      "Check AI score and highlight ChatGPT text with speed-meter radial score gauge 100% in your browser.",
    url: `${siteUrl}/ai-text-detector`,
  },
};

const removedItems = [
  {
    character: "Sentence Uniformity Check",
    unicode: "Length Variance",
    description: "Flags sentences whose length nearly matches the paragraph average — a common structural tell in AI-generated prose.",
  },
  {
    character: "Burstiness Monotony",
    unicode: "Sentence Length",
    description: "Measures how much sentence lengths vary across the whole text. Low variation (a monotonous rhythm) is scored as AI-typical.",
  },
  {
    character: "AI Cliché Phrase Density",
    unicode: "Delve, Tapestry, Realm",
    description: "Flags overused RLHF training phrases (delve, tapestry, testament to, furthermore).",
  },
  {
    character: "Passive AI Structure",
    unicode: "is / was + verb + by",
    description: "Identifies formal passive voice patterns common in automated AI drafts.",
  },
];

const howToSteps = [
  {
    title: "Paste Draft Text",
    description: "Paste content generated by ChatGPT, Claude, Gemini, or Copilot into the raw text input.",
  },
  {
    title: "Check AI Probability",
    description: "Our browser engine scores sentence-length burstiness, cliché phrase density, and passive voice live.",
  },
  {
    title: "Inspect Highlights & Humanize",
    description: "Review color-coded sentence badges and click 'Humanize & Copy' to sanitize your writing.",
  },
];

const faqs = [
  {
    question: "How does this AI Text Detector work?",
    answer:
      "Our AI Text Detector analyzes sentence length variance (burstiness), passive voice structure, and overused AI cliché phrases (delve, tapestry, realm, testament to) to compute a Human vs AI probability estimate.",
  },
  {
    question: "Is my text saved or uploaded to cloud servers?",
    answer:
      "No! Processing runs 100% locally in your browser memory. Zero text is logged, uploaded, or stored.",
  },
  {
    question: "Which AI models can this detector identify?",
    answer:
      "It detects structural writing patterns characteristic of ChatGPT (GPT-3.5/GPT-4o), Claude 3.5 Sonnet, Google Gemini, Microsoft Copilot, and open-source LLMs.",
  },
  {
    question: "Can I humanize detected AI text with one click?",
    answer:
      "Yes. Click 'Humanize & Copy Text' to strip robotic clichés and restore natural human sentence variation.",
  },
];

const webAppJsonLd = {
  "@context": "https://schema.org",
  "@type": "WebApplication",
  name: "AI Text Detector",
  url: `${siteUrl}/ai-text-detector`,
  description: "Free online AI text detector to check ChatGPT, GPT-4, Claude, and Gemini text.",
  applicationCategory: "UtilitiesApplication",
  operatingSystem: "Any",
  offers: {
    "@type": "Offer",
    price: "0",
    priceCurrency: "USD",
  },
};

const faqJsonLd = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: faqs.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: {
      "@type": "Answer",
      text: faq.answer,
    },
  })),
};

export default function AITextDetectorPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <AIDetectorUI
        heading="Free AI Text Detector (ChatGPT, GPT-4, Claude & Gemini)"
        subheading="Check if your text was generated by AI models in seconds. Highlight overused clichés, sentence monotony, and passive-voice patterns."
      />
      <SubToolContent
        title="AI Text Detector"
        directAnswerTitle="How to Detect AI Generated Text & Analyze Writing Probability"
        directAnswerText="AI text models generate language by calculating highest-probability next words, which creates distinct writing fingerprints: uniform sentence lengths (low burstiness), passive voice constructions, and reliance on specific RLHF clichés ('delve into', 'vibrant tapestry', 'testament to'). Our client-side AI Text Detector highlights these exact markers in real-time."
        beforeExample="In today's fast-paced world, artificial intelligence serves as a testament to human innovation. Furthermore, delving into this digital realm allows us to foster pivotal advancements."
        afterExample="AI Probability: 92% | Human Score: 8% | 3 Clichés Highlighted"
        removedItems={removedItems}
        howToSteps={howToSteps}
        faqs={faqs}
      />
    </>
  );
}
